### PR TITLE
Fix PHPCS errors and warnings in metabox-related files to improve code quality

### LINKED ISSUE #196: With COT enabled, multiple PHP notices are displayed when updating/saving an order linked to a subscription
## Describe the bug

With COT enabled, updating/saving an order via the Edit Order page results in the following PHP notices:

image

The backtrace points to the following functions which are accessing subscription/order properties which:
 - `WCS_Admin_Meta_Boxes->remove_meta_box_save`
 - `WCS_Meta_Box_Schedule::save`
 - `WCS_Meta_Box_Subscription_Data::save`

We should change these to just `$object->get_type()`.

## To Reproduce

1. Enable COT on your store (see [guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Purchase a subscription
3. Make note of the parent order ID
4. Got to **WooCommerce > Orders > Edit Order** for the order just purchased
5. Update the status of the order to on-hold and hit "Update"
6. Notice the errors at the top of the page

### Expected behavior

No errors are to be shown after updating an order.

### Fixed by

- [x] #280 
- [x] #281 
- [x] #282

### PR DESCRIPTION
**Pull request by Jinksi**
Related to #196

## Description

This PR fixes code-quality issues in some files related to #279, such as PHPCS errors, spelling mistakes and potential security vulnerabilities.

This PR intends to separate these changes from other PRs that otherwise would add unnecessary cognitive load for code reviewers. This will also allow future devs to make changes to this file without fixing unrelated phpcs errors (or `git commit --no-verify`).

No changes to features or logic are expected.

## How to test this PR

1. Checkout this repo and run `composer install`.
2. Run the following terminal command:
   ```
   ./vendor/bin/phpcs includes/admin/class-wcs-admin-meta-boxes.php includes/admin/meta-boxes/class-wcs-meta-box-schedule.php includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php
   ```
   - There should be no warnings or errors reported. (running `phpcs` directly from `./vendor/bin/` skips the "only changed LOC" rule that we use for PHPCS GH checks.
4. Conduct basic smoke-testing.
   - With HPOS disabled, you should see the related orders metabox in wp-admin for subscriptions and subscription-related orders.

## Product impact

- [x] Added changelog entry **does not apply**
- [x] Will this PR affect WooCommerce Subscriptions? **no**
- [x] Will this PR affect WooCommerce Payments? **no**
- [x]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0) **none**

### CODE REVIEW

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 1]
```diff
@@ -310,14 +318,14 @@ private static function can_renewal_order_be_retried( $order ) {
 
 		$can_be_retried = false;
 
-		if ( wcs_order_contains_renewal( $order ) && $order->needs_payment() && '' != wcs_get_objects_property( $order, 'payment_method' ) ) {
+		if ( wcs_order_contains_renewal( $order ) && $order->needs_payment() && '' != wcs_get_objects_property( $order, 'payment_method' ) ) { // phpcs:ignore WordPress.PHP.StrictComparisons.LooseComparison
```
Comment (shendy-a8c) [inline includes/admin/class-wcs-admin-meta-boxes.php:321]: I was like 'why not just change `!=` to `!==`'.

Then I tried:
```
var_dump('' != 0);
var_dump('' !== 0);
```

and it prints
```
bool(false)
bool(true)
```

Not worth the risk of rewriting that.

**Review by shendy-a8c — APPROVED** [review]
Wow, that is a lot of changes. Tested well per instructions.

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 1 above)
Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php:321]: Thanks @shendy-a8c. Yeh, I wanted to avoid changing any behaviour.

I think this PHPCS rule helps improve code quality for future commits, but I agree that there is not much benefit in rewriting cases where we risk breaking the existing logic.

**Comment by Jinksi** [comment]
Thanks @shendy-a8c!

> Wow, that is a lot of changes

Do you think this was too many changes, i.e. would it have been easier for you if I had broken this up into smaller PRs?

**Comment by shendy-a8c** [comment]
> would it have been easier for you if I had broken this up into smaller PRs?

No, I think it's a good size.

It is a very good decision to break https://github.com/Automattic/woocommerce-subscriptions-core/pull/279 into smaller PRs though.
