### PR TITLE
Fix manual renewal order payments via the checkout block not associating with the subscription

### LINKED ISSUE #456: Block Based Checkout Fails to Associate Order with Subscription
## Describe the bug

When using block-based checkout in WooCommerce an issue occurs where a renewal order is created during the checkout process and it is not associated with the subscription. Normally paying for a failed renewal should resume the order payment, rather than create a new one. 

## To Reproduce

1. Activate the following plugins: WooCommerce, WooCommerce Subscriptions, any Gateway (eg Stripe).
1. Create a block based checkout page. 
   - New page
   - `/checkout` block
   - Save 
   - Make note of the page URL.
2. Make sure you have 2 shipping method options.
3. Purchase a subscription.
4. Create a pending renewal order for the subscription.
5. Navigate to the subscription details page and click the "Pay" button.
7. Proceed through the checkout process using block-based checkout.
8. Change the chosen shipping method.
9. Process the checkout. 
10. Observe that an order is created, but it is not associated with the subscription.

## Expected Behavior
When using block-based checkout, the order created during the checkout process should be correctly associated with the subscription.

## Actual Behavior
With block-based checkout enabled, the order created during checkout is not associated with the subscription.

## Additional Information
Disabling block-based checkout and using the [woocommerce_checkout] shortcode resolves the issue, and the order is correctly associated with the subscription.

There are a couple of functions which are used to ensure that when a customer pays for a failed renewal order that the existing order gets resumed rather than a new order being created. For the block based checkout, there must be a gap in this. 

Check the following functions:

- `WCS_Cart_Renewal::set_order_awaiting_payment()`
- `WCS_Cart_Renewal::update_cart_hash()`

The expectation is that when WC core determines if a new order should be created or if it should be resumed they use a cart hash system. On the standard checkout we update the cart hash right before WC makes the cart hash comparison to ensure that they match. We need to check how this works with the block checkout.

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #456

## Description

When you pay for a failed or manual renewal order Subscriptions does a couple of things to make sure you resume payment of the original order, not create a new one. 

Those two are:

1. Set the `'order_awaiting_payment'` and `'store_api_draft_order'` session keys to set the order being paid. 
2. Ensure that the cart hash is updated in a way that when WC verifies whether the order being paid for is compatible with the cart changes, it returns true. We achieve that by updating the cart has stored on the order right before WC runs that check, effectively bypassing that "feature" completely.

The issue with the block checkout centres on point 2 from above. In the Store API (used by checkout blocks), there are very few hooks that trigger before the cart hash condition that we can use to bypass it. 

So, in order to fix renewal orders being paid via a block checkout, I used the `$order->has_status( 'checkout-draft' )` check [here](https://github.com/woocommerce/woocommerce-blocks/blob/9a8cec35af6fbabfbf4b25a77297d1514387e4e4/src/StoreApi/Utilities/DraftOrderTrait.php#L58-L61).

When the block checkout validates the order being paid for, it [checks if it has a `checkout-draft` status](https://github.com/woocommerce/woocommerce-blocks/blob/4dd92c3e8d047dfead8135575b2d444c2ab3085d/src/StoreApi/Utilities/DraftOrderTrait.php#L59). The order in our case will be pending-payment or failed and so it fails that condition, falling through to the cart hash logic. On `trunk` it fails that one too because of slight changes (eg shipping method) made during the checkout process. 

In order to ensure that the renewal order is valid for payment, this PR uses the `woocommerce_order_has_status` filter to make sure that when a renewal order is checked if it has a `checkout-draft` status, it will update the cart hash ensuring it's valid for payment resumption via a block checkout.

## How to test this PR

1. Create a page with a block checkout.
2. Make sure you have at least 2 shipping methods.
3. Purchase a subscription.
4. Go to the edit admin screen for the subscription.
5. From the actions dropdown select "Create pending renewal order"
6. Save
7. Attempt to pay for the newly created pending renewal order.
9. Make sure to use the checkout block page. 
10. Change the chosen shipping method
    - On `trunk` a new order will be created that isn't linked to the original subscription. And the pending renewal order will be left pending.
    - On this branch, the original renewal order will be paid without creating a new order.

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wcs-cart-renewal.php [hunk 1]
```diff
@@ -429,7 +434,23 @@ public function get_cart_item_from_session( $cart_item_session_data, $cart_item,
...
+				if ( isset( $subscription_items[ $cart_item_session_data[ $this->cart_item_key ]['line_item_id'] ] ) ) {
+					$item_to_renew = $subscription_items[ $cart_item_session_data[ $this->cart_item_key ]['line_item_id'] ];
+				} else {
+					foreach ( $subscription_items as $item ) {
+						if ( $item->get_meta( '_cart_item_key_' . $this->cart_item_key, true ) === $key ) {
+							$item_to_renew = $item;
+							break;
+						}
+					}
+				}
```
Comment (james-allan) [inline includes/class-wcs-cart-renewal.php:453]: These changes were necessary because for some reason, when the order line items are deleted and then readded, all attempts to update the cart items with the latest line item IDs (see `set_cart_item_order_item_id()`) failed to work. 

This would result in errors like this:


```
PHP Warning:  Undefined array key 3265 in /woocommerce-subscriptions-core/includes/class-wcs-cart-renewal.php on line 435
```

These errors occur because once the line item has been deleted and re-added during the the cart item reference to the old item is still intact leading it to try locate its corresponding item via an ID that no longer exists. 

To get around that I've added an alternative fallback approach which locates the line item by finding the cart item key that is stored in line item meta. 

ie the cart item corresponds to the order line item which has cart item's key as meta

Screenshot 2023-08-15 at 5 35 30 pm

**Review by mattallan — CHANGES_REQUESTED** [review]
I have pushed up the small changes we discussed IRL which updates our function hooked onto `has_status` so that it now updates the `cart_hash` property on the order instead of just returning `true`.

This is a little more robust as the previous implementation relied on other 3rd party code not hooking onto `woocommerce_order_has_status` later than us and returning `false`.

I've confirmed the bug on `trunk` and confirmed fixed on the latest changes on this PR.

- [x] Needs a changelog entry

**Comment by james-allan** [comment]
@mattallan do you mind giving this another look? I had to make a couple of changes since your last review. 

I've updated `set_cart_hash()` to be able to receive an order object - not just an ID. With the changes in https://github.com/Automattic/woocommerce-subscriptions-core/pull/498/commits/e2011014e3ca9bbb8b5abe0b89e07b309433aae1 the logic in `DraftOrderTrait::is_valid_draft_order()` was still failing because the cart hash was being updated on a different instance of the order.

By updating the cart hash on the same exact same order object passed to the `woocommerce_order_has_status` filter we can make sure that logic passes.

**Review by mattallan — APPROVED** [review]
@james-allan I've reproduced the issue on `trunk` and confirmed it's fixed with your latest changes. LGTM!
