### PR TITLE
Deprecate and remove cached shipping rates for recurring carts and related functions

### LINKED ISSUE #400: Incorrect package caching triggers conflicts with various extensions
## Describe the bug

When calculating rates for packages, Subscriptions uses a caching mechanism to store rates per package and avoid calling `WC()->shipping->calculate_shipping_for_package` multiple times: https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-cart.php#L1257-L1267

`WC()->shipping->calculate_shipping_for_package` has its own caching mechanism that uses the entire $package in order to produce the hash key to avoid calculating rates multiple times: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-shipping.php#L333

Subscriptions uses only some of the $package keys to create the hash key (contents/contents cost and applied coupons): https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-cart.php#L1277 

The reason behind this seems to be that Subscriptions wants to apply the same Shipping rates to all recurring packages in the cart to boost performance. However, this triggers conflicts with Conditional Shipping and Payments, Product Bundles, and Composite Products. 

**For Conditional Shipping and Payments:** 

This plugin can be used to filter shipping rates in recurring packages based on their billing schedule. When Subscriptions is caching the package, it doesn't take into account its recurring schedule. Therefore, packages with identical contents but different schedules end up having the same rates. This prevents Conditional Shipping and Payments from disabling specific rates per package. 

**For Product Bundles/ Composite Products together with All Products for WooCommerce Subscriptions:** 

All Products for WooCommerce Subscriptions enables content switching for subscribed Bundles. These switches are always considered cross-grades, as proration for content switching is not supported. 

When switching a subscribed bundle, the initial package with $0 subtotal (cross-grade) gets cached and the rates calculated for this package are passed down to the recurring package as well (as contents, content totals, and applied coupons are identical). If a Free Shipping Method has a minimum order restriction, then it doesn't show up for the recurring package because Subscriptions uses the rates of the initial package for the recurring one as well -- and the subtotal of the initial package is $0.

Therefore, it seems that the optimization Subscriptions has implemented for caching packages, by creating hashes using only some of its keys, is causing more issues than benefits. A couple of solutions here are: 
- When caching packages, cache the entire package similarly to what core does. 
- Fall back the core package caching system.

## To Reproduce

See linked issues for detailed replication steps: 
- https://github.com/woocommerce/woocommerce-product-bundles/issues/1134
- https://github.com/woocommerce/woocommerce-conditional-shipping-and-payments/issues/534

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #400 

## Description

Back in 2016 we introduced a caching layer to avoid fetching available shipping rates multiple times in a single request. You can find the original issue and PR here for reference: 

- https://github.com/woocommerce/woocommerce-subscriptions/issues/1415
- woocommerce/woocommerce-subscriptions#1485

The original motivation for us was purely performance. It's hard to tell that far in the past but today WC core has caching of shipping rates. Whether this caching layer existed back then is unclear - it does look like there was at the very least some cache ([wc 2.6.0 ref](https://github.com/woocommerce/woocommerce/blob/2.6.0/includes/class-wc-shipping.php#L330-L331)).

The original issue didn't include any statistics on the impact on load times or performance, it specifically called out that there are 3-4 calls to get the shipping rates all on 1 load. 

A lot of time has passed since 2016 and there have been a number of improvements to WooCommerce core with a focus on performance over the years. Given this passage of time and the impact this cache is having on third-party compatibility, I've done a review of this cache and removing it hasn't lead to any meaningful performance hit that I've been able to measure or any change in behaviour.

With that in mind, this PR removes the shipping rate cache layer in favour of calling the WC core function directly. 

## How to test this PR

1. Set up shipping methods.
    - It's best to have a variety of free, and flat rate methods. 
3. Add subscription and or simple products to your cart and test whether the shipping methods displayed on checkout and the cart page are as expected. 
4. Complete the purchase and make sure shipping methods and totals are set on the subscriptions matching the choices.
5. Test a variety of different cart and shipping setups.

To test this PR during development, I kept the caching layer intact and compared the value stored in the cache with the value returned from WC core's function directly. In my testing, the result never differed.

## Product impact

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [x]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

cc @jimjasson

### CODE REVIEW

File: includes/class-wc-subscriptions-cart.php [hunk 1]
```diff
@@ -1529,6 +1472,38 @@ public static function add_to_cart_redirect( $url ) {
...
+	 *
+	 * @deprecated 5.4.0
+	 *
+	 * @param array $rates A set of WC_Shipping_Rate objects.
+	 * @param array $package A shipping package in the form returned by @see WC_Cart->get_shipping_packages()
+	 * @return array $rates An unaltered set of WC_Shipping_Rate objects passed to the function
+	 * @since 1.0.0 - Migrated from WooCommerce Subscriptions v2.0.18
+	 */
+	public static function cache_package_rates( $rates, $package ) {
+		_deprecated_function( __METHOD__, '5.4.0' );
```
Comment (mattallan) [inline includes/class-wc-subscriptions-cart.php]:
```suggestion
		_deprecated_function( __METHOD__, 'subscriptions-core 5.4.0' );
```

File: includes/class-wc-subscriptions-cart.php [hunk 2]
```diff
@@ -1529,6 +1472,38 @@ public static function add_to_cart_redirect( $url ) {
...
+	 * If there are no rates stored in the cache for this package, it will fall back to @see WC_Shipping::calculate_shipping_for_package()
+	 *
+	 * @deprecated 5.4.0
+	 *
+	 * @param array $package A shipping package in the form returned by @see WC_Cart->get_shipping_packages()
+	 * @return array $package
+	 * @since 1.0.0 - Migrated from WooCommerce Subscriptions v2.0.18
+	 */
+	public static function get_calculated_shipping_for_package( $package ) {
+		_deprecated_function( __METHOD__, '5.4.0', 'WC()->shipping->calculate_shipping_for_package()' );
```
Comment (mattallan) [inline includes/class-wc-subscriptions-cart.php]:
```suggestion
		_deprecated_function( __METHOD__, 'subscriptions-core 5.4.0', 'WC()->shipping->calculate_shipping_for_package()' );
```

**Review by mattallan — APPROVED** [review]
Nice changes @james-allan, I thought this was going to be a more complicated review to do but I was surprised by how straightforward the changes were to remove the shipping cache.

I tested various shipping options on the cart and checkout (including local pickup, free for orders over $50, flat rate) as well as throwing virtual products into the mix and didn't find any issues with recurring packages being calculated, nor did I notice any performance hit.

I made a few small suggestions with putting the subscriptions core string in the deprecated version to be consistent with our other deprecations.
