### PR TITLE
Fix admin notices missing when HPOS enabled 

### LINKED ISSUE #641: Admin notices missing when HPOS enabled
## Describe the bug
When HPOS is enabled, Admin notices such as "2 subscription statuses changed" are not shown to the user after performing a Bulk action on subscriptions.

## To Reproduce

1. Ensure HPOS is enabled.
2. Go to WooCommerce --> Subscriptions to see the list of subscriptions.
3. Select one or more subscriptions in the list.
4. Go to 'Bulk actions' and select an option such as 'Move to Trash'.
5. Click Apply.

### Expected behavior
After clicking apply, an Admin Notice should be displayed giving the results of the bulk action, just like it does in legacy storage mode.

### Actual behavior
The action is performed, but no Admin notice is displayed to let the user know the results. This impact is greater when the bulk action performed doesn't otherwise produce a change you might notice in the subscription list such as triggering an email to the subscriber.

## Product impact
WooCommerce Subscriptions 6.5.0

- [X] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref

## Additional context
WooCommerce 9.1.6
WordPress 6.5.5, 6.6.0

(I thought I'd found another PR where this was fixed, but it looks like it fixed a different issue and this issue is still relevant.)

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #641 

## Description
When HPOS is enabled, Admin notices such as "2 subscription statuses changed" are not shown to the user after performing a Bulk action on subscriptions.

This was happening because `handle_bulk_actions-woocommerce_page_wc-orders--shop_subscription` filter was [returning](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/privacy/class-wcs-privacy.php#L127) `null` instead of the `redirect_url`.

## How to test this PR

1. Create a few subscriptions if you already don't have some.
2. Go to _WooCommerce > Subscriptions_ page. 
3. Select a few subscriptions, select a new status from the `Bulk actions` dropdown and apply the changes.
4. In `trunk`, notice that the statuses of the selected subscriptions have changed but there is no notice on the page.
5. Checkout to this branch and repeat step 3.
6. Confirm that the statuses of the selected subscriptions have changed and there is a notice on the page.

Screenshot 2024-07-30 at 11 43 34 AM

### CODE REVIEW

File: includes/privacy/class-wcs-privacy.php [hunk 1]
```diff
@@ -124,7 +124,7 @@ public static function add_privacy_bulk_action( $bulk_actions ) {
 	 */
 	public static function handle_privacy_bulk_actions( $redirect_url, $action, $subscription_ids ) {
 		if ( 'wcs_remove_personal_data' !== $action ) {
-			return;
+			return $redirect_url;
```
Comment (Mayisha) [inline includes/privacy/class-wcs-privacy.php:127]: This line fixes the main notice issue.

The other changes are a little refactor. As the `handle_privacy_bulk_actions` function is called by the `handle_bulk_actions-woocommerce_page_wc-orders--shop_subscription` hook as well, removed the redirection and exit from this function, moving it to the other parent (except the hook) function `process_bulk_action`.

**Review by james-allan — APPROVED** [review]
Changes look good @Mayisha. I confirmed that on `trunk` updating subscriptions via bulk actions wasn't displaying the notice. On this branch the notice is shown as expected.

Screenshot 2024-08-08 at 11 53 56 AM

File: changelog.txt [hunk 2]
```diff
@@ -2,6 +2,7 @@
 
 = 7.4.0 - 2024-xx-xx =
 * Update - Schedule subscription-related events with a priority of 1 to allow for earlier execution within the Action Scheduler.
+* Fix - Ensure admin notices are displayed after performing bulk actions on subscriptions when HPOS is enabled.
```
Comment (james-allan) [inline changelog.txt:5]: @Mayisha Just noting I added this changelog entry as one was missing. Feel free to tweak it. 🙂

Comment (Mayisha) [reply changelog.txt:5]: Thanks James 🍫
