### PR TITLE
Use `wc_wp_theme_get_element_class_name()` instead of hardcoding the `wp-element-button` class name

### LINKED ISSUE #569: Add support for additional classes for the add to cart button
## Describe the bug

WooCommerce added support for additional classes in the add to cart button 15 months go, this is still not reflected in the Woo Subs add to cart custom buttons, causing a broken style.

```php
<button type="submit" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>" class="single_add_to_cart_button button alt<?php echo esc_attr( wc_wp_theme_get_element_class_name( 'button' ) ? ' ' . wc_wp_theme_get_element_class_name( 'button' ) : '' ); ?>"><?php echo esc_html( $product->single_add_to_cart_text() ); ?></button>
```

image
image

## To Reproduce

1. In 2024 theme, go to a subscription product page, see the button is without styles.
2. Go to a regular product page, see that the button has regular styles.

### Expected behavior
Subscription button should match the regular button styles.

### Actual behavior
Button is without styles.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #569 

## Description

In https://github.com/Automattic/woocommerce-subscriptions-core/pull/574 we merged a small change to fix the styling of our "Sign up now" on subscription product pages for stores using a block theme (i.e. 2024 default theme).

This PR tweaks the code slightly to use `wc_wp_theme_get_element_class_name()` instead of hardcoding the `wp-element-button` class name.

The `wc_wp_theme_get_element_class_name()` function was added to WooCommerce Core in v7.0.1 which is below our minimum supported version so no need to check this function exists.

## How to test this PR

> [!NOTE]
> Since we already fixed the button styling issue in a previous PR, there won't be any noticeable issues to confirm are fixed in this PR. Instead we'll just be checking our sign up buttons contain the correct class names.

1. Activate the 2024 default theme
2. Visit a simple subscription and confirm the page is styled correctly.
3. Inspect the Sign up button and confirm it contains the `'wp-element-button'` class name:
image

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: templates/single-product/add-to-cart/subscription.php [hunk 1]
```diff
@@ -39,16 +38,18 @@
...
+				'max_value'   => apply_filters( 'woocommerce_quantity_input_max', $product->get_max_purchase_quantity(), $product ),
+				'input_value' => isset( $_POST['quantity'] ) ? wc_stock_amount( wp_unslash( $_POST['quantity'] ) ) : $product->get_min_purchase_quantity(), // phpcs:ignore WordPress.Security.NonceVerification.Missing -- input var ok.
+			]
+		);
 
 		do_action( 'woocommerce_after_add_to_cart_quantity' );
 		?>
 
-		<button type="submit" class="single_add_to_cart_button button alt wp-element-button" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>"><?php echo esc_html( $product->single_add_to_cart_text() ); ?></button>
+		<button type="submit" class="single_add_to_cart_button button alt<?php echo esc_attr( wc_wp_theme_get_element_class_name( 'button' ) ? ' ' . wc_wp_theme_get_element_class_name( 'button' ) : '' ); ?>" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>"><?php echo esc_html( $product->single_add_to_cart_text() ); ?></button>
```
Comment (james-allan) [inline templates/single-product/add-to-cart/subscription.php:52]:
```suggestion
		<button type="submit" class="single_add_to_cart_button button alt<?php echo wc_wp_theme_get_element_class_name( 'button' ) ? ' ' . esc_attr( wc_wp_theme_get_element_class_name( 'button' ) : '' ); ?>" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>"><?php echo esc_html( $product->single_add_to_cart_text() ); ?></button>
```

Happy to approve without this change, but this caught my eye. The way this is written, the whole ternary is inside the `esc_attr()` call and so if the condition is false, it will escape an empty string ('') or a space plus the class `'  wp-element-button'`. While this is doesn't cause any issues, it didn't seem right to me. 

The proposed change just escapes the variable part of this, the `wc_wp_theme_get_element_class_name()` output.

**Review by james-allan — APPROVED** [review]
The changes work for me. I've confirmed the `wp-element-button` class is still included on sign up buttons for both simple and variable subscription products and that the buttons are styled correctly.

File: templates/single-product/add-to-cart/subscription.php (hunk 1 above)
Comment (mattallan) [reply templates/single-product/add-to-cart/subscription.php:52]: Thanks @james-allan for the review. I thought this too, but then I noticed WooCommerce core code escapes the whole ternary everywhere they call this function. I can't think of a reason why, but I followed suit 😄 

The suggested code has a syntax issue due to the closing `)` for the `esc_attr` not being correct, so I think I'll just leave it for now in favour of keeping it the same as WooCommerce core.
