### PR TITLE
Fixes for showing/hiding other gateways express payment buttons on product pages

### LINKED ISSUE #81: Available payment methods are not being filtered on Product Pages
## Describe the bug

PayPal Checkout smart payment buttons and Stripe Payment Request buttons (Apple & Google Pay) are being shown on subscription product pages when the WC Subscriptions extension is not active.

This is a bug because WooCommerce Payments should be the only available payment method when using the free subscriptions feature.

image

In `subscriptions-core`, we [filter the list of available payment methods](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/gateways/class-wc-subscriptions-core-payment-gateways.php#L66-L86) to only return WooCommerce Payments and in [Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/db1b192326dd8bd9062c58c10a98e607e3d50de3/includes/payment-methods/class-wc-stripe-payment-request.php#L803-L807) and [PayPal Express Checkout](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/70b75bfb30475e60475a00dcd30bfd39723c84a4/includes/class-wc-gateway-ppec-cart-handler.php#L307) I can see that they're checking if their gateway is available before rendering these buttons.

The reason they're still loading on subscription product pages is because our logic in [`WC_Subscriptions_Core_Payment_Gateways::get_available_payment_gateways()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/gateways/class-wc-subscriptions-core-payment-gateways.php#L72-L78) doesn't filter the list of gateways when viewing the subscription product page.

## To Reproduce

1. Make sure the WC Subscriptions extension is deactivated
2. Activate WC Payments + Subscriptions feature, Stripe, PayPal Checkout
3. Setup and enable all three payment gateways (enable express payment methods on WCPay/Stripe and Smart Buttons on PayPal Checkout)
4. Create a subscription product if you don't have one
5. View the Subscription Product page
6. Notice the PayPal Smart Payment Buttons and Stripe express buttons incorrectly being shown 🔴 
7. Add a subscription product to your cart and view the page again.
8. Notice only WC Payments express buttons are shown 🟢  

### Expected behavior

PayPal Smart Payment Buttons and Stripe express payment buttons shouldn't be shown on subscription product pages when WooCommerce Payments is the only available payment method.

I think the solution here is to add some logic [here](https://github.com/Automattic/woocommerce-subscriptions-core/blob/10555008c58cd08b3e3bd353b04de8dc55de475c/includes/gateways/class-wc-subscriptions-core-payment-gateways.php#L72-L78) which checks `is_product()` and not a subscription product.

If it's a subscription product, we want to make sure to only return WooCommerce Payments.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions?
   - WC Subscriptions is not affected because we don't filter the list of available payment methods.
- [x] Does this issue affect WooCommerce Payments? Yes
  - https://github.com/Automattic/woocommerce-payments/issues/3401

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #81 

## Description

This PR is fixing a few issues around `get_available_payment_methods()` not being filtered on product pages. For some background, `subscriptions-core` filters this WC function to make sure only WC Payments is the only available when the cart contains a subscriptions.

On `trunk` there are two known issues caused by this area of code:
- Viewing a WC simple product with a subscription product in cart doesn't show any Stripe or PayPal express payment buttons on product page :x:
- Viewing a subscription product was incorrectly loading the Stripe and PayPal express payment buttons on the page :x:

These issue have been fixed with this PR:

- Subscription product pages don't show other gateway buttons ✅ 
- Mini-cart widget still shows other gateway buttons if the cart contains WC simple products ✅ 
image

- WC simple product pages now show other gateways buttons when there's a subscription product in cart
image

## How to test this PR

1. Make sure WC Subscriptions plugin is deactivated
1. Enable WCPay Subscriptions feature
1. Install and activate the Stripe gateway
   - Enable express payment buttons
1. Install and activate the PayPal Checkout gateway (you'll have to setup a PayPal sandbox account if you don't have one yet)
   - Make sure the PayPal Buttons are being shown on product, cart, checkout and mini-cart
1. View a subscription product page and confirm no Stripe Google Pay or PayPal buttons are being shown
1. View a WC simple product page and confirm Stripe Google Pay and PayPal buttons are loading

---

Test cases I've ran:
 - Viewing a Simple Product with an empty cart 🟢
 - Viewing a Simple Product with subscription in cart 🟢
 - Viewing a Variable Product page 🟢
 - Viewing a Subscription Product page 🟢
 - Viewing a Variable Subscription page 🟢
 - Cart page with no subscription 🟢
 - Cart page with a subscription 🟢
 - Checkout page with a subscription 🟢
 - Checkout page with no subscription 🟢

## Product impact

- ✅  Added changelog entry (or does not apply)
- :x: Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- ✅  Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
  - https://github.com/Automattic/woocommerce-payments/issues/3401

### CODE REVIEW

**Comment by haszari** [comment]
@mattallan FYI I requested review from Helix – assuming this is ready for reviews!

**Comment by brucealdridge** [comment]
@mattallan is this issue/pr specifically for [PayPal Checkout](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout)? I installed it and noticed it was deprecated so tested instead with [WooCommerce PayPal Payments](https://github.com/woocommerce/woocommerce-paypal-payments/) and was able to purchase a subscription product from the mini-cart.

**Comment by mattallan** [comment]
> is this issue/pr specifically for PayPal Checkout?

Yeah, this PR is specifically targetting fixes for Stripe and PayPal Checkout see https://github.com/Automattic/woocommerce-payments/issues/3401#issuecomment-999366086. Apologies that wasn't clear from the PR description 😅 


PayPal Payments doesn't check if their payment gateway is available before loading the buttons (which feels like a bug) so we/Axiom will need to patch that plugin to fix this problem.

**Comment by james-allan** [comment]
This looks good to me. 

I tested the following scenarios: 

With **WC Subscriptions inactive**: 

1. Shown on WC Simple product. 👍 
2. Shown on the cart page with a simple product in the cart. 👍 
2. Shown on WC Simple product page with subscription product in the cart. 👍 
3. Not shown on the subscription product page. 👍 
4. Not shown on the subscription product page with a simple product in the cart. 👍 
3. Not shown on cart page with a subscription. 👍 

With the **WC Subscriptions plugin active**, I tested that it basically gets shown all the time in all contexts.


---

Just for completeness, I wasnt 100% convinced of the `widget_title` action handling, however, after looking at PayPal Checkout's code and looking for alternative hooks, I couldn't find anything that would work.

We could patch PayPal Checkout but we'd still have problems on old versions and that plugin has been deprecated and perhaps isn't even maintained anymore so would be a strange fix there.

**Review by james-allan — APPROVED** [review]

File: includes/gateways/class-wc-subscriptions-core-payment-gateways.php [hunk 1]
```diff
@@ -291,6 +317,44 @@ public static function gateway_supports_subscriptions( $gateway ) {
 		return ! empty( $gateway->id ) && 'woocommerce_payments' === $gateway->id;
 	}
 
+	/**
+	 * The PayPal Checkout plugin checks for available payment methods on this hook
+	 * before enqueuing their SPB JS when displaying the buttons in the mini-cart widget.
+	 *
+	 * This function is hooked on to 0 priority to make sure we set $is_displaying_mini_cart to true before displaying the mini-cart.
+	 *
+	 * @since 1.4.0
```
Comment (james-allan) [inline includes/gateways/class-wc-subscriptions-core-payment-gateways.php]:
```suggestion
	 * @since 1.5.0
```

File: includes/gateways/class-wc-subscriptions-core-payment-gateways.php [hunk 2]
```diff
@@ -291,6 +317,44 @@ public static function gateway_supports_subscriptions( $gateway ) {
...
+		return $title;
+	}
+
+	/**
+	 * The PayPal Checkout plugin checks for available payment methods on this hook
+	 * before enqueuing their SPB JS when displaying the buttons in the mini-cart widget.
+	 *
+	 * This function is hooked on to priority 1000 to make sure we set $is_displaying_mini_cart back to false after any JS is enqueued for the mini-cart.
+	 *
+	 * @since 1.4.0
```
Comment (james-allan) [inline includes/gateways/class-wc-subscriptions-core-payment-gateways.php]:
```suggestion
	 * @since 1.5.0
```

**Review by james-allan — CHANGES_REQUESTED** [review]
Just two tiny changes requested. :)

**Comment by mattallan** [comment]
Thanks @james-allan and @aprea ! The latest changes/suggestions LGTM. Merging this

**Comment by shendy-a8c** [comment]
@mattallan I see that the added changelog has [2 similar entries](https://github.com/Automattic/woocommerce-subscriptions-core/pull/87/files#diff-b40cd67182487ef24807d9c9268329d35fbd96aa2b0a9cae69e2e0d746b1c666R4-R5). Not sure if it's intentional.

Update: Matt already answered over Slack. Those 2 changelog entries are for 2 different things, so nothing needs to be changed.
