### PR TITLE
[HPOS] Refactor `WCS_Meta_Box_Subscription_Data::save` to fix PHP notices that occur when updating an order via the Edit Order page

### LINKED ISSUE #196: With COT enabled, multiple PHP notices are displayed when updating/saving an order linked to a subscription
## Describe the bug

With COT enabled, updating/saving an order via the Edit Order page results in the following PHP notices:

image

The backtrace points to the following functions which are accessing subscription/order properties which:
 - `WCS_Admin_Meta_Boxes->remove_meta_box_save`
 - `WCS_Meta_Box_Schedule::save`
 - `WCS_Meta_Box_Subscription_Data::save`

We should change these to just `$object->get_type()`.

## To Reproduce

1. Enable COT on your store (see [guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Purchase a subscription
3. Make note of the parent order ID
4. Got to **WooCommerce > Orders > Edit Order** for the order just purchased
5. Update the status of the order to on-hold and hit "Update"
6. Notice the errors at the top of the page

### Expected behavior

No errors are to be shown after updating an order.

### Fixed by

- [x] #280 
- [x] #281 
- [x] #282

### PR DESCRIPTION
**Pull request by Jinksi**
Partially fixes #196

> **Warning**
> Blocked from merging until after subs-core 5.1.0 release.

This branch is based on #280.

## Description

This PR fixes PHP notices related to `WCS_Meta_Box_Subscription_Data::save` that occur when updating an order via the Edit Order page with HPOS enabled.

## How to test this PR

0. [Enable HPOS](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos).
2. Purchase a Subscription product, noting the order ID.
3. Go to WooCommerce → Orders and navigate to the order's Edit Order page.
4. Select a new order **status** (processing/pending payment) and click update.
5. The order should update successfully and you should not see PHP notices related to **`WCS_Meta_Box_Subscription_Data::save`**.
		(There may be others, e.g. `WCS_Meta_Box_Schedule::save`).
3. Go to WooCommerce → Subscriptions and navigate to a subscription's Edit Subscription page.
4. Select a new subscription status (on hold/active) and click update.
5. The subscription should update successfully and you should not see PHP notices related to **`WCS_Meta_Box_Subscription_Data::save`**.
		(There may be others, e.g. `WCS_Meta_Box_Schedule::save`).
6. Disable HPOS and repeat steps 2-7
	(WC Settings → Advanced → Custom data stores →  Use the WordPress posts table)

**Note**: you may see the following error when setting a Subscription status to `on-hold` with HPOS enabled, syncing disabled. A new issue has been created for this: #293

```
Invalid data. First parameter was empty when passed to update_dates().
```

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php [hunk 1]
```diff
@@ -427,6 +433,6 @@ public static function save( $post_id, $post = null ) {
 			do_action( 'woocommerce_admin_created_subscription', $subscription );
 		}
 
-		do_action( 'woocommerce_process_shop_subscription_meta', $post_id, $post );
+		do_action( 'woocommerce_process_shop_subscription_meta', $post_or_order_id, $post_or_order_object );
```
Comment (Jinksi) [inline includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php]: Need to consider deprecating this hook.

Since the source of these args are coming from the WC hook ([ref](https://github.com/woocommerce/woocommerce/blob/a8bafb5255a6750eb4494f23d0a9d0d5d0126505/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php#L152)), I'm unsure if it's required here. Only the name of the variables are changing within subs-core code.

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 2]
```diff
@@ -97,11 +97,15 @@ public function remove_meta_boxes() {
...
+	 *
+	 * @see woocommerce_process_shop_order_meta
+	 *
+	 * @param int $post_or_order_id
+	 * @param WC_Order|WP_Post $post_or_order_object
 	 */
-	public function remove_meta_box_save( $post_id, $post ) {
-
-		if ( 'shop_subscription' === $post->post_type ) {
+	public function remove_meta_box_save( $post_or_order_id, $post_or_order_object ) {
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-meta-boxes.php]:
```suggestion
	public function remove_meta_box_save( $subscription_id, $subscription ) {
```

Small nit-pick: I don't think we need to specify that this is a post or order in the variable name because when WC moves away entirely from WP Posts we will have to go back and rename these variables. I think we should stick to naming these variables what we expect them to be i.e. `$order_id` or `$subscription_id`, or just `$id` in a general sense and `$order`, `$subscription` or `$object`.

If we expect the object/id to be both an order and/or subscription we can just use `$order`.

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Ah, good point, thanks. I was preferring to use `$post_or_order_object` under the influence of the [HPOS upgrade guide](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos), although I see that with many WC-specific hooks, only `$order` will be provided.

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Addressed in bfa5da3 and d2d0694

File: changelog.txt [hunk 3]
```diff
@@ -8,6 +8,7 @@
 * Fix - On HPOS stores, when a subscription is loaded from the database, make sure all core subscription properties are read directly from meta.
 * Fix - When viewing My Account > Subscriptions, fix an issue where no subscriptions were listed when HPOS is enabled.
 * Fix - On HPOS stores, ensure payment tokens are copied from the subscription to the renewal order.
+* Fix - Refactor `WCS_Meta_Box_Subscription_Data::save` to support HPOS stores, fixing a PHP warning notice when updating an order via the Edit Order screen.
```
Comment (Jinksi) [inline changelog.txt]: Unsure whether to keep 2 similar changelog entries separate (line 11 + line 12) or merge into one.

Comment (shendy-a8c) [reply changelog.txt]: I think it's OK to keep 2 similar changelog entries.

**Review by shendy-a8c — APPROVED** [review]
Looks good. Now I don't see any PHP notices when editing Subscription.

**Comment by shendy-a8c** [comment]
Adding status blocked so it's not merged before our planned release of `subscriptions-core` 5.1.

**Comment by shendy-a8c** [comment]
> [Move changelog entry to 5.2.0](https://github.com/Automattic/woocommerce-subscriptions-core/pull/281/commits/78941a5bd7d0b7a44deb54c671f9f3ef2b07865f)

Nice!
