### PR TITLE
[HPOS] Bulk actions missing from Subscriptions listing in wp-admin

### LINKED ISSUE #321: [HPOS] Bulk actions missing on Subscriptions List
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) bulk actions are not displaying the correct actions.

Blocked by https://github.com/woocommerce/woocommerce/issues/35750 as we are unable to test new bulk actions work.

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. Click on the 'Bulk actions' drop down and compare the options when the store is in CPT mode.

**CPT**
image
**HPOS**
image

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #321

> **Note**
> This PR is targeting the `hpos-admin-ui-support` branch due to the changes required for admin screens in HPOS environments awaiting merge

## Description

Bulk actions are missing from the Subscriptions listing page in wp-admin when HPOS is enabled.

NB: Bulk actions will not work with this PR, there is an open issue for this  https://github.com/woocommerce/woocommerce/issues/35750.

There was a small refactor to go along with this change. Previously, the function `print_bulk_actions_script()` appends the Subscription bulk actions to the dropdown list using jquery. 
This was due to the `bulk_actions-edit-shop_subscription` previously not allowing the addition of items but only the removal. This restriction [was dropped](https://developer.wordpress.org/reference/hooks/bulk_actions-this-screen-id/#more-information) in WP 4.7.0 (2016-12-06.)

**CPT**
image
**HPOS**
image

## How to test this PR

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) 

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. Click on the 'Bulk actions' drop down and compare the options when the store is in CPT mode.
## Product impact

- [x] Added changelog entry (or does not apply) - This will be rolled up into one changelog entry for admin screens working under HPOS.
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Comment by brucealdridge** [comment]
~A changelog has not been added yet as it maybe some time before this gets merged.~ 
This will be rolled up into one changelog entry for admin screens working under HPOS.

**Comment by brucealdridge** [comment]
phpcs style check is failing due to issues on the source PR. They will be resolved there.

File: includes/admin/class-wcs-admin-post-types.php [hunk 1]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
-	 * string. The same array is used to
+	 * Remove "edit" from the bulk actions.
 	 *
+	 * @param array $actions
+	 * @return array
 	 */
-	public function print_bulk_actions_script() {
+	public function filter_bulk_actions( $actions ) {
+		// 'post_status' is used in CPT datastore, 'status' is used in HPOS datastore.
+        // phpcs:ignore WordPress.Security.NonceVerification.Recommended,WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]: Rather than ignore these phpcs errors, should we address them?

Or we could comment with the reason why ignoring is preferable.

File: includes/admin/class-wcs-admin-post-types.php [hunk 2]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
+			function( $action_key ) use ( $actions_to_remove ) {
+				return ! in_array( $action_key, $actions_to_remove, true );
+			},
+			ARRAY_FILTER_USE_KEY
+		);
 
-		if ( 'shop_subscription' !== get_post_type() || in_array( $post_status, array( 'cancelled', 'trash', 'wc-expired' ) ) ) {
-			return;
+		// If we are currently in trash, expired or cancelled listing. We don't need to add subscriptions specific actions.
+		if ( in_array( $post_status, array( 'cancelled', 'trash', 'wc-expired' ), true ) ) {
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
		if ( in_array( $post_status, [ 'cancelled', 'trash', 'wc-expired' ], true ) ) {
```
Nitpick: change to short array syntax.

File: includes/admin/class-wcs-admin-post-types.php [hunk 3]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
+	 * @param array $actions
+	 * @return array
 	 */
-	public function print_bulk_actions_script() {
+	public function filter_bulk_actions( $actions ) {
+		// 'post_status' is used in CPT datastore, 'status' is used in HPOS datastore.
+        // phpcs:ignore WordPress.Security.NonceVerification.Recommended,WordPress.Security.ValidatedSanitizedInput.MissingUnslash,WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
+		$post_status = $_GET['post_status'] ?? $_GET['status'] ?? '';
+
+		// List of actions to remove that are irrelevant for subscriptions
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
		// List of actions to remove that are irrelevant for subscriptions.
```

Nit: fullstop at end of comment.

File: includes/admin/class-wcs-admin-post-types.php [hunk 4]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
+		$actions_to_remove = array(
+			'edit',
+			'mark_processing',
+			'mark_on-hold',
+			'mark_completed',
+			'mark_cancelled',
+		);
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
		$actions_to_remove = [
			'edit',
			'mark_processing',
			'mark_on-hold',
			'mark_completed',
			'mark_cancelled',
		];
```
Nit: use short array syntax.

File: includes/admin/class-wcs-admin-post-types.php [hunk 5]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
 
-		$post_status = ( isset( $_GET['post_status'] ) ) ? $_GET['post_status'] : '';
+		// Remove actions that are not relevant for subscriptions.
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
		// Remove actions that are not relevant to subscriptions.
```
Nit: Update wording.

File: includes/admin/class-wcs-admin-post-types.php [hunk 6]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
 	/**
-	 * Add extra options to the bulk actions dropdown
-	 *
-	 * It's only on the All Shop Subscriptions screen.
-	 * Introducing new filter: woocommerce_subscription_bulk_actions. This has to be done through jQuery as the
-	 * 'bulk_actions' filter that WordPress has can only be used to remove bulk actions, not to add them.
-	 *
-	 * This is a filterable array where the key is the action (will become query arg), and the value is a translatable
-	 * string. The same array is used to
+	 * Remove "edit" from the bulk actions.
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]: Should we explain in this docblock that this function:
* also removes other order actions, e.g. `mark_cancelled`.
* adds new subscription-related actions.

**Review by Jinksi — APPROVED** [review]
This tests well, @brucealdridge 🎉

I've tested the following and see the correct output for both Subscriptions (inc trashed) and orders.

- [x] HPOS disabled
- [x] HPOS enabled + no sync
- [x] HPOS enabled + sync

image

I've left a few suggestions, but they are all nitpicky, so feel free to take or leave as you see fit.

File: includes/admin/class-wcs-admin-post-types.php [hunk 7]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
 	 *
+	 * @param array $actions
+	 * @return array
 	 */
-	public function print_bulk_actions_script() {
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-post-types.php:268]: We will need to deprecate this function

File: includes/admin/class-wcs-admin-post-types.php [hunk 8]
```diff
@@ -244,57 +244,69 @@ public function remove_bulk_actions( $actions ) {
...
+				unset( $actions['active'] );
 				break;
 			case 'wc-on-hold':
-				unset( $bulk_actions['on-hold'] );
+				unset( $actions['on-hold'] );
 				break;
 		}
 
-		?>
-		<script type="text/javascript">
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-post-types.php:283]: Apologies if this is obvious but do we need to load these scripts anymore? Even on older versions of WooCommerce?

**Review by mattallan — APPROVED** [review]
I've only performed code review on this one (i'll do more testing on all of this as once it's in the feature branch).

I only picked up on one issue with respect to backwards compatibility, other than that this is looking good! Thanks @brucealdridge

File: includes/admin/class-wcs-admin-post-types.php (hunk 1 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: There is no nonce on the status filters so we will need to ignore that. The others can be addressed however.

File: includes/admin/class-wcs-admin-post-types.php (hunk 7 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php:268]: addressed in cb3416a5

File: includes/admin/class-wcs-admin-post-types.php (hunk 6 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: addressed in 225e2ad3

File: includes/admin/class-wcs-admin-post-types.php (hunk 5 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: 225e2ad3

File: includes/admin/class-wcs-admin-post-types.php (hunk 4 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: addressed in 225e2ad3

File: includes/admin/class-wcs-admin-post-types.php (hunk 3 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: addressed in 225e2ad3

File: includes/admin/class-wcs-admin-post-types.php (hunk 2 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: addressed in 225e2ad3

File: includes/admin/class-wcs-admin-post-types.php (hunk 1 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: I've kept the nonce ignore, removed the others and made sure to unslash and sanitize the field. 

Given we're keeping the nonce ignore, I've added a note about why we're ignoring it. 

commit: 225e2ad3

**Comment by shendy-a8c** [comment]
Update: Nevermind, after running `composer install`, no more problem.

~I see this warning `Warning: Undefined array key "post_status" in /Users/sk/github/Automattic/woocommerce-subscriptions-core/includes/admin/class-wcs-admin-post-types.php on line 273` on `/wp-admin/admin.php?page=wc-orders--shop_subscription`.~

Screenshot 2022-12-20 at 03 04 34

~I see this warning when HPOS is enabled, using WC orders table, with sync on.~

**Comment by shendy-a8c** [comment]
> phpcs style check is failing due to issues on the source PR. They will be resolved there.

I believe no PR that fixes the phpcs warnings yet. I'm opening https://github.com/Automattic/woocommerce-subscriptions-core/pull/352. Let me know if someone else has been working on that.

**Comment by james-allan** [comment]
> Update: Nevermind, after running composer install, no more problem.

Nah I think that's a legit issue. Because I wrapped the double ternaries in `wp_unslash()` and sanitize, it broke it. I'll get that patched up.

**Comment by james-allan** [comment]
>  I'll get that patched up.

I've fixed that error in [239dea4](https://github.com/Automattic/woocommerce-subscriptions-core/pull/327/commits/239dea4134a4f09f5275007d93f64821d6f2b2ab)

**Comment by shendy-a8c** [comment]
Ah right. I think I switched branch and saw the error disappeared. [239dea4](https://github.com/Automattic/woocommerce-subscriptions-core/pull/327/commits/239dea4134a4f09f5275007d93f64821d6f2b2ab) fixes it.

**Comment by james-allan** [comment]
Merged into the base branch in the interest of moving this along and getting us to the stage where we can test all these changes together and start creating new issues.
