### PR TITLE
Remove all get_post_type() from WC_Subscriptions_Manager.

### LINKED ISSUE #288: [HPOS] Replace `get_post_type()` with WC_Data_Store::load( 'subscription' )->get_order_type( $id )
## Describe the bug

To support subscriptions stored in different data stores, we need to replace all cases of `get_post_type()` with `WC_Data_Store::load( 'subscription' )->get_order_type( $id )`.

Doing a search of `get_post_type(` in `subscriptions-core` code there's 15 instances of this still being used.

In #153 we only targetted code which used this function on WC Orders, but as part of tackling this issue we should replace all cases.

---

#### Updating `get_post_type( $subscription_id )`

```
'shop_subscription' == get_post_type( $post_id )
```

Replace with:

```
'shop_subscription' === WC_Data_Store::load( 'subscription' )->get_order_type( $id )
```

#### Updating `get_post_type( $product_id )`

I could only find one instance where we're using `get_post_type()` with product ID inside `user_can_not_delete_subscription()`

```
0 === strpos( get_post_type( $args[2] ), 'product' )
```

The issue with`WC_Data_Store::load( 'product' )->get_product_type( $id )` is that it formats product types i.e. `'product_variation'` is returned as just `'variation'` so there's not a simple one-to-one replacement for this one.

We can probably just ignore this one case for now.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Partially fixes https://github.com/Automattic/woocommerce-subscriptions-core/issues/288.

## Description

Replace `get_post_type()` usage from `WC_Subscriptions_Manager`.

## How to test this PR

Not sure what's the best way to test but I use WP Console to call the affected function directly, eg `WC_Subscriptions_Manager::maybe_cancel_subscription( $id )`.
I tested with $id that belongs to a subscription and one that does not. Also, I tested with HPOS disabled and enabled and with WC version 6.8 (prior HPOS).

Note: I haven't added a changelog. Will add one after 5.1 is released.

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wc-subscriptions-manager.php [hunk 1]
```diff
@@ -841,20 +841,29 @@ public static function maybe_delete_subscription( $post_id ) {
...
 
-		if ( 'shop_subscription' == get_post_type( $post_id ) && 'auto-draft' !== get_post_status( $post_id ) ) {
+		$subscription = wcs_get_subscription( $id );
+		if ( ! $subscription ) {
+			return;
+		}
 
-			$subscription = wcs_get_subscription( $post_id );
+		// Check its type because $subscription might be WC_Subscription's child class.
+		if ( $subscription->get_type() !== 'shop_subscription' ) {
```
Comment (mattallan) [inline includes/class-wc-subscriptions-manager.php:854]: Call `wcs_get_subscription()` checks if the subscription is a subscription so we don't need to check the type here now.

File: includes/class-wc-subscriptions-manager.php [hunk 2]
```diff
@@ -841,20 +841,29 @@ public static function maybe_delete_subscription( $post_id ) {
...
+			return;
+		}
 
-			if ( $subscription->can_be_updated_to( 'cancelled' ) ) {
+		if ( 'auto-draft' === $subscription->get_status() ) {
```
Comment (mattallan) [inline includes/class-wc-subscriptions-manager.php]: @james-allan recently changed our `$subscription->set_status()` function (https://github.com/Automattic/woocommerce-subscriptions-core/pull/258) to always make sure 'auto-draft' and 'draft' isn't set as the subscriptions status when it's read from the DB so I don't think we need this check in here anymore.

i.e if I run the following code:

```
$id = 503;

wp_update_post( [ 'ID' =>  $id, 'post_status' => 'draft' ] );
$subscription = wcs_get_subscription( $id );
echo $subscription->get_status() . "\n";

wp_update_post( [ 'ID' =>  $id, 'post_status' => 'auto-draft' ] );
$subscription = wcs_get_subscription( $id );
echo $subscription->get_status();
```

It shows `get_status()` always returns `'pending'` when the status is auto-draft/draft

File: includes/class-wc-subscriptions-manager.php [hunk 3]
```diff
@@ -868,26 +877,36 @@ public static function maybe_cancel_subscription( $post_id ) {
...
-	public static function fix_trash_meta_status( $post_id ) {
+	public static function fix_trash_meta_status( $id ) {
+
+		$subscription = wcs_get_subscription( $id );
+		if ( ! $subscription ) {
+			return;
+		}
+
+		// Check its type because $subscription might be WC_Subscription's child class.
+		if ( $subscription->get_type() !== 'shop_subscription' ) {
```
Comment (mattallan) [inline includes/class-wc-subscriptions-manager.php:885]: As above, calling `wcs_get_subscription( $id );` returns `false` if the object isn't a subscription type so we don't need to check this after fetching the subscription object.

**Review by mattallan — CHANGES_REQUESTED** [review]
Thanks @shendy-a8c!

I've tested the following flows that are impacted by these changes:
 - [x] When trashing an active subscription, make sure the subscription is canceled first
 - [x] After a subscription is trashed make sure `_wp_trash_meta_status` is set to `wc-cancelled`

I've tested the following changes on WC 7.2 with HPOS disabled and also WC 6.8.

This code doesn't need to be tested on HPOS-enabled sites as we're still hooking onto `wp_trash_post` and `before_delete_post`. These will be addressed in https://github.com/Automattic/woocommerce-subscriptions-core/issues/221


---

I've made a few comments to clean up some of these functions:
 - [ ] We don't need to call `$subscription->get_type() !== 'shop_subscription'` after fetching the subscription using `wcs_get_subscription()`
 - [ ] We don't need to check `'auto-draft' === $subscription->get_status()` since the subscription status will be returned as `'pending'` for draft statuses.
 - [ ] Changelog is needed

File: includes/class-wc-subscriptions-manager.php (hunk 1 above)
Comment (shendy-a8c) [reply includes/class-wc-subscriptions-manager.php:854]: Isn't is possible another plugin maybe extends `WC_Subscription` and the returned value of `wcs_get_subscription()` is the child class of `WC_Subscription`?

Consider this code:
```
$subscription = wcs_get_subscription( 56 );

class WC_Subscription_Child extends WC_Subscription {
    public function __construct( $subscription = 0 ) {
		parent::__construct( $subscription );
		$this->order_type = 'shop_subscription2';
	}
	
	public function get_type() {
		return $this->order_type;
	}
}

wc_register_order_type(
	'shop_subscription2',
	apply_filters(
		'woocommerce_register_post_type_subscription',
		array(
			'class_name' => 'WC_Subscription_Child',
		)
	)
);

$a = wcs_get_subscription( 111111 );
var_dump( $a->get_type() );

$wc_subscription_child = new WC_Subscription_Child( 111111 );
$b = new WC_Subscription_Child( $wc_subscription_child );
var_dump( $b->get_type() );
```

where order with id 56 is a WC_Subscription but 111111 I manually inserted
```
INSERT INTO wp_wc_orders (id, status, currency, type) VALUES (111111, 'wc-active', 'USD', 'shop_subscription2');
```

The PHP code will print `shop_subscription2`. Hence, I thought checking the type and make sure we only handle `shop_subscription` is necessary.

File: includes/class-wc-subscriptions-manager.php (hunk 2 above)
Comment (shendy-a8c) [reply includes/class-wc-subscriptions-manager.php]: Thank you for pointing that out! Addressed in 057fa07abfbc5c016574e6534529fbac7dd15f87.

I was wondering if it would affect this PR when I read a changelog entry yesterday that says:
```
Replaces the need for the overriding WC_Subscription::get_status() which has been deleted.
```

**Comment by shendy-a8c** [comment]
> Changelog is needed

Addressed in 27ba924bebcf5d057834db7530893758a4f82800.

File: includes/class-wc-subscriptions-manager.php (hunk 1 above)
Comment (mattallan) [reply includes/class-wc-subscriptions-manager.php:854]: Good point :) Let's leave the type check in there.

File: includes/class-wc-subscriptions-manager.php [hunk 4]
```diff
@@ -868,26 +873,36 @@ public static function maybe_cancel_subscription( $post_id ) {
...
 	 */
-	public static function fix_trash_meta_status( $post_id ) {
+	public static function fix_trash_meta_status( $id ) {
+
+		$subscription = wcs_get_subscription( $id );
+		if ( ! $subscription ) {
+			return;
+		}
+
+		// Check its type because $subscription might be WC_Subscription's child class.
```
Comment (mattallan) [inline includes/class-wc-subscriptions-manager.php]: > WC_Subscription's child class.

I don't think we need to emphasize that this check is for custom subscription types. I don't think we need this comment but if we want to keep it, we can just say something like: 

```suggestion
		// Check the object type is shop_subscription
```

Comment (shendy-a8c) [reply includes/class-wc-subscriptions-manager.php]: Sounds good! Addressed in [6a1f79c](https://github.com/Automattic/woocommerce-subscriptions-core/pull/305/commits/6a1f79c17117d8599b8bd34f627c4252c9d5df34)

**Review by mattallan — APPROVED** [review]
Thanks Shendy! This one is good to merge
