### PR TITLE
HPOS Admin UI support

### LINKED ISSUE #223: Admin screens (List, Create, and Edit) broken with HPOS enabled.
## Describe the bug

Listing, Editing, and Creation of Subscriptions from wp-admin are broken when HPOS is enabled. 

In WooCommerce Core with HPOS enabled Create, Update and Listing of orders use a different URL/controller than when using custom post types (see code sample below). This is also required for Subscriptions

https://github.com/woocommerce/woocommerce/blob/8fbdbaf3540786deeb4fc7d6b8d57a6b4b5dea6c/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php#L259-L263

This is currently being worked on in WooCommerce Core: https://github.com/woocommerce/woocommerce/issues/35601

## To Reproduce

1. With HPOS enabled, go to 'Subscriptions'
2. Click on 'Add Subscription.
3. See error.

### Expected behavior

Manual subscriptions can be created in wp-admin.

### Actual behavior

A fatal error is generated
```
Fatal error: Uncaught Error: Call to a member function get_items() on bool in wp-content/plugins/woocommerce-subscriptions-core/includes/class-wc-subscriptions-synchroniser.php:1148 
Stack trace: 
#0 wp-includes/class-wp-hook.php(309): WC_Subscriptions_Synchroniser::maybe_add_subscription_meta(371) 
#1 wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) 
#2 wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#3 wp-includes/post.php(4673): do_action('save_post', 371, Object(WP_Post), false) 
#4 wp-admin/includes/post.php(700): wp_insert_post(Array, false, false) 
#5 wp-admin/post-new.php(66): get_default_post_to_edit('shop_subscripti...', true) 
#7 {main} thrown in wp-content/plugins/woocommerce-subscriptions-core/includes/class-wc-subscriptions-synchroniser.php on line 1148
```

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### LINKED ISSUE #293: Schedule metabox does not display when HPOS is enabled
## Describe the bug

Related to #223.

The Schedule metabox does not render when HPOS is enabled, and syncing is disabled.

This has an additional side-effect of throwing the following error when updating a Subscription to status: `on-hold`: see https://github.com/Automattic/woocommerce-subscriptions-core/pull/282#issuecomment-1322434040.

```
Invalid data. First parameter was empty when passed to update_dates().
```

## To Reproduce

1. Enable [HPOS](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos) and disable syncing (see settings screenshot).
2. Purchase a subscription via BACS or WCPay. Note the Order ID and Subscription ID.
3. View the subscription. Currently, Subscriptions are not visible via the List screen (see #223) with HPOS enabled and syncing off. View the screen via the URL `/wp-admin/admin.php?page=wc-orders&action=edit&id={{subcription_id}}`
4. Notice that the **Schedule** metabox is not visible.

image

### Expected behavior

Screenshot 2022-11-22 at 10-07-29 Edit Subscription “Subscription” ‹ subs-core-hpos — WordPress

The Schedule metabox should be visible on the Edit Subscription screen when HPOS is enabled and syncing disabled.

### Actual behavior

The Schedule metabox is not visible on the Edit Subscription screen when HPOS is enabled and syncing disabled.

Screenshot 2022-11-22 at 10-06-53 Orders ‹ subs-core-hpos — WordPress

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes
- [x] Does this issue affect WooCommerce Payments? yes

## Additional context

Discovered in https://github.com/Automattic/woocommerce-subscriptions-core/pull/282#issuecomment-1322434040.

Method that outputs metabox:
https://github.com/Automattic/woocommerce-subscriptions-core/blob/b65106656cc0c44167da6e21af9277655eabf186/includes/admin/meta-boxes/class-wcs-meta-box-schedule.php#L19-L30

`add_meta_box` called here:
https://github.com/Automattic/woocommerce-subscriptions-core/blob/b65106656cc0c44167da6e21af9277655eabf186/includes/admin/class-wcs-admin-meta-boxes.php#L80

### LINKED ISSUE #298: [HPOS] Edit Subscription admin screen: Function post_excerpt was called incorrectly
## Describe the bug

A php notice is thrown on the edit subscription admin screen.

```
Notice: Function post_excerpt was called incorrectly. Order properties should not be accessed directly. 

Backtrace: require('wp-admin/admin.php'), 
do_action('woocommerce_page_wc-orders--shop_subscription'), 
WP_Hook->do_action, 
WP_Hook->apply_filters, 
Automattic\WooCommerce\Internal\Admin\Orders\PageController->output, 
Automattic\WooCommerce\Internal\Admin\Orders\Edit->display, 
Automattic\WooCommerce\Internal\Admin\Orders\Edit->render_meta_boxes, 
do_meta_boxes, 
WCS_Meta_Box_Subscription_Data::output, 
WC_Subscription->__get, 
WC_Abstract_Legacy_Order->__get, 
wc_doing_it_wrong
```

## To Reproduce

1. With HPOS enabled and set as the default order storage, edit a subscription in /wp-admin/
2. See the error

image

### LINKED ISSUE #321: [HPOS] Bulk actions missing on Subscriptions List
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) bulk actions are not displaying the correct actions.

Blocked by https://github.com/woocommerce/woocommerce/issues/35750 as we are unable to test new bulk actions work.

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. Click on the 'Bulk actions' drop down and compare the options when the store is in CPT mode.

**CPT**
image
**HPOS**
image

### LINKED ISSUE #322: [HPOS] Viewing Subscriptions admin screen, customer filter is too short
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) the filter by a registered customer is too short to read.

image

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. See the customer filter is too short.

### PR DESCRIPTION
**Pull request by brucealdridge**
> **Warning**
> This PR is semi-blocked by upstream changes in WC https://github.com/woocommerce/woocommerce/pull/35658 these changes should be okay to merge prior to this but need these changes for testing.

fixes #293 
fixes #223 
fixes #298
fixes #322
fixes #321

## Description

PR bringing a number of fixes to Admin UI based on the changes introduced in https://github.com/woocommerce/woocommerce/pull/35658
 

## How to test this PR

**HPOS** 

⚠️ **Important**: Parts of this flow will be broken and errors will be thrown. For HPOS this PR is aimed at laying the groundwork. File any usability issues you come across while testing. 

1. Enable HPOS tables. 
2. Purchase subscriptions. 
3. Go to the **WooCommerce > Subscriptions** admin screen. 
4. Note that the page loads and subscriptions are listed. 
6. Click on a subscription to edit it. 
7. Note the page loads. 

**CPT**

⚠️ **Important**: This PR shouldn't break any CPT flows or UIs. This PR needs to be releasable to existing CPT stores.

1. Enable CPT tables. 
2. Purchase subscriptions. 
3. Go to the **WooCommerce > Subscriptions** admin screen. 
4. Note that the page loads and subscriptions are listed. 
    - Filter by customer
    - Filter by product
    - filter by status
    - use the bulk actions
    - use the individual actions by hovering a subscription (suspend, reactivate etc). 
6. Click on a subscription to edit it. 
8. Note the page loads. 
     - Change the billing schedule
     - Change the subscription data (change the customer, parent order, address data etc.) 
9. Save and make sure things save correctly. 

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Comment by brucealdridge** [comment]
Thanks for your work on this @jorgeatorres 
Now that we can test these HPOS flows a few more minor areas of work have revealed themselves. I've logged #298 #299 #300 #301 as bugs

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 1]
```diff
@@ -94,8 +95,7 @@ public function add_meta_boxes( $post_type = '', $post_or_order_object = null )
 		}
 
 		// Get "Edit Order" screen ID, which differs if HPOS is enabled.
-		$screen         = wcs_is_custom_order_tables_usage_enabled() ? wc_get_page_screen_id( 'shop-order' ) : 'shop_order';
-		$current_screen = get_current_screen();
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php:98]: The `$current_screen` variable has inadvertently been removed here (I think). It is used by the if statement below.

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php:98]: Will be resolved in #347

File: includes/admin/class-wc-subscriptions-admin.php [hunk 2]
```diff
@@ -839,7 +839,8 @@ public static function enqueue_styles_scripts() {
 		// Get admin screen id
 		$screen = get_current_screen();
 
-		$is_woocommerce_screen = in_array( $screen->id, array( 'product', 'edit-shop_order', 'shop_order', 'edit-shop_subscription', 'shop_subscription', 'users', 'woocommerce_page_wc-settings', 'woocommerce_page_wc-orders' ), true );
+		$subscriptions_screen_id = wc_get_page_screen_id( 'shop_subscription' );
```
Comment (mattallan) [inline includes/admin/class-wc-subscriptions-admin.php]: This function doesn't exist in older versions of WC. So we'll need to change this to something similar to what we've done in other areas of this PR:

```suggestion
		$subscriptions_screen_id = wcs_is_custom_order_tables_usage_enabled() ? wc_get_page_screen_id( 'shop_subscription' ) : 'shop_subscription';
```

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 3]
```diff
@@ -78,14 +78,15 @@ public function __construct() {
 	 * @param WP_Post|WC_Order|null $post_or_order_object The post or order currently being edited.
 	 */
 	public function add_meta_boxes( $post_type = '', $post_or_order_object = null ) {
+		$subscriptions_screen_id = wcs_is_custom_order_tables_usage_enabled() ? wc_get_page_screen_id( 'shop_subscription' ) : 'shop_subscription';
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-meta-boxes.php]: Small nit-pick but the `wcs_is_custom_order_tables_usage_enabled()` is called multiple times in this function so we should pull it out into it's own variable

File: includes/admin/class-wcs-admin-post-types.php [hunk 4]
```diff
@@ -892,6 +923,14 @@ public function request_query( $vars ) {
 		return $vars;
 	}
 
+	public function request_query_hpos( $vars ) {
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-post-types.php]: Missing docblock

File: includes/admin/class-wcs-admin-post-types.php [hunk 5]
```diff
@@ -1203,4 +1254,67 @@ protected static function get_item_display_div( $item, $item_name, $item_meta_ht
...
+	 * Introducing new filter: woocommerce_subscription_bulk_actions. This has to be done through jQuery as the
+	 * 'bulk_actions' filter that WordPress has can only be used to remove bulk actions, not to add them.
+	 *
+	 * This is a filterable array where the key is the action (will become query arg), and the value is a translatable
+	 * string. The same array is used to
+	 *
+	 * @deprecated 5.3.0
+	 */
+	public function print_bulk_actions_script() {
+		wcs_deprecated_function( __METHOD__, '5.3.0' );
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
		wcs_deprecated_function( __METHOD__, 'subscriptions-core 5.3.0' );
```

**Comment by james-allan** [comment]
Just noting that I'll be taking the role of author of this PR and addressing feedback.

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 3 above)
Comment (mattallan) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Actually, we should check when `wc_get_page_screen_id()` was introduced instead of using `wcs_is_custom_order_tables_usage_enabled()`.

This will help later on with cleaning out outdated code once we remove support for WC x.x

Comment (james-allan) [reply includes/admin/class-wcs-admin-meta-boxes.php]: I've introduced a compat wrapper instead. See [cb67744](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297/commits/cb67744512065b194d732d10cd7273813dbb2d77) and [c223624](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297/commits/c22362481c344dc7c4e2c389d9f20060005747f9)

File: includes/admin/class-wc-subscriptions-admin.php (hunk 2 above)
Comment (james-allan) [reply includes/admin/class-wc-subscriptions-admin.php]: Resolved in [c223624](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297/commits/c22362481c344dc7c4e2c389d9f20060005747f9).

File: includes/admin/class-wcs-admin-post-types.php (hunk 4 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: addressed in abd1ceef. 

I ended up changing the name of this function because it wasn't obvious to me what it was intended to do.

**Comment by mattallan** [comment]
Tests I've ran:

**No HPOS**
 - [x] Confirmed admin lists subscriptions loads
 - [x] Confirmed customer, payment method filters
 - [x] Confirmed status filters work (including trash)
 - [x] Edit Subscription page loads
 - [x] Can manually edit subscription status and order items
 - [x] Add Subscription page loads
 - [x] Creating a subscription with WC Payments, adding order items and updating dates all work as expected.

**HPOS on**
- [x] Confirmed admin lists subscriptions loads
- [ ] Confirmed customer, payment method filters :x: (open issue https://github.com/Automattic/woocommerce-subscriptions-core/issues/334)
- [ ] Confirmed status filters work :x:
- [ ] Edit Subscription page loads :x:
   - Schedule meta box below notes and actions (open issue https://github.com/Automattic/woocommerce-subscriptions-core/issues/338)
   - Schedule meta box has PHP warnings (open issue https://github.com/Automattic/woocommerce-subscriptions-core/issues/299)
 - [ ] Add Subscription page loads :x: (same issues as Edit screen)

Of the issues I've found. None of them impact CPT (existing admin screens) so I'm thinking this branch is safe for us to merge and start fixing the remaining issues in separate PRs instead of using this as a base branch.

Just needs a changelog entry.

File: includes/admin/class-wcs-admin-post-types.php [hunk 6]
```diff
@@ -592,8 +622,9 @@ public function render_shop_subscription_columns( $column ) {
 				} elseif ( $the_subscription->get_billing_first_name() || $the_subscription->get_billing_last_name() ) {
 					$username = trim( $the_subscription->get_billing_first_name() . ' ' . $the_subscription->get_billing_last_name() );
 				}
+
 				// translators: $1: is opening link, $2: is subscription order number, $3: is closing link tag, $4: is user's name
-				$column_content = sprintf( _x( '%1$s#%2$s%3$s for %4$s', 'Subscription title on admin table. (e.g.: #211 for John Doe)', 'woocommerce-subscriptions' ), '<a href="' . esc_url( admin_url( 'post.php?post=' . absint( $post->ID ) . '&action=edit' ) ) . '">', '<strong>' . esc_attr( $the_subscription->get_order_number() ) . '</strong>', '</a>', $username );
+				$column_content = sprintf( _x( '%1$s#%2$s%3$s for %4$s', 'Subscription title on admin table. (e.g.: #211 for John Doe)', 'woocommerce-subscriptions' ), '<a href="' . esc_url( wc_get_container()->get( OrderUtil::class )->get_order_admin_edit_url( $the_subscription->get_id() ) ) . '">', '<strong>' . esc_attr( $the_subscription->get_order_number() ) . '</strong>', '</a>', $username );
```
Comment (james-allan) [inline includes/admin/class-wcs-admin-post-types.php]: Just noting that we can't do this because the OrderUtil::get_order_admin_edit_url() function was only introduced 3 months ago and won't be available on all WC versions we support. 

I'll patch that up.

File: includes/admin/class-wcs-admin-post-types.php [hunk 7]
```diff
@@ -545,8 +573,6 @@ public function render_shop_subscription_columns( $column ) {
 
 				$actions = apply_filters( 'woocommerce_subscription_list_table_actions', $actions, $the_subscription );
 
-				$column_content .= $wp_list_table->row_actions( $actions );
```
Comment (james-allan) [inline includes/admin/class-wcs-admin-post-types.php:548]: The effect of this change means that the actions are no longer displayed under the subscription status, like they use to. I'll patch this up.

File: includes/admin/class-wcs-admin-post-types.php (hunk 6 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: Fixed.

File: includes/admin/class-wcs-admin-post-types.php (hunk 7 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php:548]: This has been fixed.

**Comment by mattallan** [comment]
Making a note about this change: [ea7936a](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297/commits/ea7936a22d7b072238d7e4f2ef8f8812d1afac0d)

This function supports the WP Post do_action and HPOS do_action.

When using the CPT hook, the second parameter is an integer: https://developer.wordpress.org/reference/hooks/manage_post-post_type_posts_custom_column/

When using the HPOS hook, the second parameter is an order/subscription object:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/Orders/ListTable.php#L144

**Comment by mattallan** [comment]
Testing on the latest changes:

- [x] Enable CPT tables.
- [x] Purchase subscriptions.
- [x] Go to the WooCommerce > Subscriptions admin screen.
- [x] Note that the page loads and subscriptions are listed (Fixed with e1627cf, ea7936a & 13a3d71)
- [x] Filter by customer
- [x] Filter by product
- [x] filter by status
- [x] use the bulk actions
- [x] use the individual actions by hovering a subscription (suspend, reactivate etc).
- [x] Click on a subscription to edit it.
- [x] Note the page loads.
- [x] Change the billing schedule (Fixed with 13e77a9)
- [x] Change the subscription data (change the customer, parent order, address data etc.)
- [x] Save and make sure things save correctly.

**Review by james-allan — APPROVED** [review]
I've ran through some tests this morning prioritising CPT stores. 

I've done the following tests:

List table: 

1. Used the bulk actions to put subscriptions on-hold. 
2. Sorted the list table by next payment dates. 
3. Filtered the subscriptions list table using a product filter. 
4. Use the individual subscription actions to cancel a subscription. 

Edit screen:

1. Set a parent order
2. Changed billing address
3. changed next payment date

All tests passed.

File: changelog.txt [hunk 8]
```diff
@@ -2,6 +2,7 @@
 
 = 5.2.0 - 2022-xx-xx =
 * Add - New wcs_set_order_address() helper function to set an array of address fields on an order or subscription.
+* Fix - Admin edit/add Subscription and Subscriptions list/table pages now work when HPOS is enabled.
```
Comment (mattallan) [inline changelog.txt]:
```suggestion
* Fix - Subscription admin screens (edit, add, and list Subscription pages) now work when HPOS is enabled.
```

File: changelog.txt [hunk 9]
```diff
@@ -2,6 +2,7 @@
 
 = 5.2.0 - 2022-xx-xx =
 * Add - New wcs_set_order_address() helper function to set an array of address fields on an order or subscription.
+* Fix - Subscription admin screens (edit, add, and list Subscription pages) now work when HPOS is enabled.
```
Comment (mattallan) [inline changelog.txt]:
```suggestion
* Fix - Edit, add, and list Subscription admin pages now work when HPOS is enabled.
```

**Comment by mattallan** [comment]
Huge props to @brucealdridge and everyone involved in getting these admin screens working!
