### PR TITLE
Prevent a post record re-sync on every subscription get

### LINKED ISSUE #268: [HPOS] With data syncing enabled every subscription fetch is causing a sync
## Describe the bug

When you have HPOS tables and syncing enabled (see screenshot below). Everytime you call `wcs_get_subscription` a sync request is fired off even if things are in sync. 
 
Screen Shot 2022-11-16 at 3 59 14 pm

## To Reproduce

1. Apply the settings above.
2. Trigger any `wcs_get_subscription()` call. 
    - either view the my account view subscription page
    - using wp console call `wcs_get_subscriptions()`. 
5. Inside the `maybe_sync_order` function add a breakpoint, error log or something to let you know the `migrate_post_record()` function is being called.

You'll notice that a simple fetch subscription request is causing the post record to be synced erroneously. 

### Expected behavior

The `migrate_post_record` should only be called if things are out of sync between the HPOS & posts tables.

### Actual behavior

From the debugging I've done, I discovered that the reason for this is because `is_post_different_from_order()` returns true when the subscription is being read. 

The reason for that is because the subscription record and the subscription post record are out of date with the following diff https://www.diffchecker.com/XvgpvNvF. Notice the `schedule_start`, `schedule_next_payment`, `requires_manual_renewal`, `suspension_count`, `billing_interval` & `billing_period` are all empty in the order record but populated in the post record.

The reason for that is because of the way we set those properties. They get set on the subscription in `set_subscription_props` and that function is called from the `read_multiple` function. However this post sync check happens in the `parent::read_multiple()` and so us setting these props after the parent function is called, is too late. [code ref](https://github.com/automattic/woocommerce-subscriptions-core/blob/5.0.0/includes/data-stores/class-wcs-orders-table-subscription-data-store.php#L362-L365). 

**Can't we then call `set_subscription_props` before `parent::read_multiple()` ?**

No we can't because in the `parent::read_multiple()` function they call `init_order_record()` and in that function they `$order->set_defaults();` which sets all the subscription props to empty, they call all these other functions like `init_meta_data()` but pass filtered meta (so our dates and billing interval meta will be excluded), they call `set_order_props_from_data()` but that only sets core order data from the HPOS orders, addresses, operational database tables (our keys are in meta). And all these functions are private and so we can't override them. 

I'm not sure how we're going to fix this. We might need to reach out to Proton. 

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #268 

## Description

On HPOS sites with syncing enabled, every time `wcs_get_subscription()` is called, WC will incorrectly determine that the subscription needs to be resynced when nothing was changed. 

The reason this erroneous resync occurs this is because WC determines if syncing needs to occur in the `read_multiple()` function before we've had a chance to set our subscription specific properties. 

So the comparison WC does between the HPOS and Post subscription objects aren't the same - the HPOS one is incomplete, the POST is complete.

This PR fixes that by utilising the changes I made to WC core in https://github.com/woocommerce/woocommerce/pull/35829. This change allows us to set Subscription properties in before WC do the compare, meaning the "Do we need to resync" check runs on completely loaded objects.

## How to test this PR

As far as I could tell, this resync wasn't causing and data corruption but given this change requires changes to a fundamental part of our datastore and changes to WC core, it's important that we patch this relatively early. 

1. Install the latest WC nightly build.
1. Apply the following settings see below.
    - HPOS tables enabled.
    - Syncing enabled. 
1. Trigger any `wcs_get_subscription()` call.
      - either view the my account view subscription page
      - using wp console call `wcs_get_subscription()`.
1. Inside the `maybe_sync_order()` function add a breakpoint, error log or add something to let you know the `migrate_post_record()` function is being called.
     - On `trunk` the migrate_post_record() function is called everytime. 
     - On this branch the migrate_post_record function should only be called when something is different. You can experiment with this by manually changing a subscription property in the HPOS or WP synced post tables. 

> **Warning**
> Syncing from the post record to the HPOS record doesn't currently work for subscription dates (eg next payment date). We will need to fix this separately. 
> - https://github.com/Automattic/woocommerce-subscriptions-core/issues/355

image

## Product impact

- [ ] Added changelog entry (or does not apply)
- [X] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [X] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [X]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/data-stores/class-wcs-orders-table-subscription-data-store.php [hunk 1]
```diff
@@ -343,23 +343,6 @@ public function create( &$subscription ) {
 		do_action( 'woocommerce_new_subscription', $subscription->get_id() );
 	}
 
-	/**
-	 * Reads multiple subscription objects from custom tables.
-	 *
-	 * @param \WC_Order $subscriptions Subscription objects.
-	 */
-	public function read_multiple( &$subscriptions ) {
```
Comment (james-allan) [inline includes/data-stores/class-wcs-orders-table-subscription-data-store.php:351]: We were overriding this `read_multiple()` function only to make sure we called `set_subscription_props()` after each subscription was read. This is no longer necessary because what `set_subscription_props()` use to do is now done via `set_order_props_from_data()` which is called during the read.

**Review by mattallan — APPROVED** [review]
I confirmed the bug on `trunk` with subscription objects always being synced and confirmed it's fixed on this branch.

I also changed some subscription meta via the DB and then ran `wcs_get_subscription()` to confirm that data syncing is still working.

LGTM
