### PR TITLE
Fix issues causing caches on HPOS sites with sync off to not update

### LINKED ISSUE #194: Spike: Avoid `_post` hooks in `WCS_Post_Meta_Cache_Manager` (e.g. `update_post_meta`, `trashed_post`)
> **Note** - As part of tackling this issue, we will need to investigate what's broken and possible solutions.

## Describe the bug

From the COT upgrade guide, there's a section on [auditing our code](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#auditing-the-code-base-for-direct-db-access-usage):

> To support custom order tables, a good place to start is to audit your code base for direct DB access and usage of WordPress APIs that we won't be using any more. You can search using following regexes to perform this audit

Using their regex string, one area of code that was highlighted was our `WCS_Post_Meta_Cache_Manager` class.
This class's [init function](https://github.com/Automattic/woocommerce-subscriptions-core/blob/9ce5295854ff935426b13e8e216265f10f06ec41/includes/class-wcs-post-meta-cache-manager.php#L37) hooks onto various post updated/added/deleted and meta changed hooks to then make sure our related order cache is updated properly:

```
// When the post for a related order is deleted or untrashed, make sure the corresponding related order cache is updated
add_action( 'before_delete_post', array( $this, 'post_deleted' ) );
add_action( 'trashed_post', array( $this, 'post_deleted' ) );
add_action( 'untrashed_post', array( $this, 'post_untrashed' ) );

// When a related order post meta flag is modified, make sure the corresponding related order cache is updated
add_action( 'added_post_meta', array( $this, 'meta_added' ), 10, 4 );
add_action( 'update_post_meta', array( $this, 'meta_updated' ), 10, 4 );
add_action( 'deleted_post_meta', array( $this, 'meta_deleted' ), 10, 4 );

// Special handling for meta updates containing a previous order ID to make sure we also delete any previously linked relationship
add_action( 'update_post_metadata', array( $this, 'meta_updated_with_previous' ), 10, 5 );

// Special handling for meta deletion on all posts/orders, not a specific post/order ID
add_action( 'delete_post_metadata', array( $this, 'meta_deleted_all' ), 100, 5 );
I haven't witnessed any issues with testing our plugin yet but under the heading of "Auditing our code yet but 
```

I haven't tested broken flows with us using these old hooks with COT enabled on the store so part of tackling this issue is also investigating impact.

My understanding is that these hooks just won't fire anymore when a store is using Custom Order Tables meaning our related order cache won't update properly but we'll need to confirm.

### LINKED ISSUE #283: With HPOS enabled and sync off, My account > Subscriptions does not show purchased subscriptions
## Describe the bug

My account > Subscriptions page (/my-account/subscriptions/) does not show purchased subscriptions under these conditions:
- HPOS enabled
- WooCommerce orders table is used as the data store for orders
- Sync off

It works with sync on or if data store is using WordPress posts table.

## To Reproduce

1. Make sure custom orders tables are created. wp-admin > WooCommerce > Status > Tools > Create the custom orders tables.

2. Make sure HPOS is enabled. wp-admin > WooCommerce > Settings > Advanced > Enable the high performance order storage feature.

If the `Enable the high performance order storage feature` checkbox is disabled, create a PHP file for example `wp-content/mu-plugins/something.php` and add this code:

```
add_action('woocommerce_init', function () {
    if (class_exists('\Automattic\WooCommerce\Utilities\FeaturesUtil')) {
        \Automattic\WooCommerce\Utilities\FeaturesUtil::allow_enabling_features_with_incompatible_plugins();
        \Automattic\WooCommerce\Utilities\FeaturesUtil::allow_activating_plugins_with_incompatible_features();
    }
});
```

The `Enable the high performance order storage feature` checkbox should now be checkable.

3. Make sure to use WooCommerce orders tables as the order data store. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > Choose `Use the WooCommerce orders tables` and keep `Keep the posts table and the orders tables synchronized` unchecked.

4. Purchase a subscription product.

5. As customer, go to My account > Subscriptions page (/my-account/subscriptions/).

### Expected behavior

The newly purchased subscription is shown on My account > Subscriptions page (/my-account/subscriptions/).

### Actual behavior

The newly purchased subscription is not showing on My account > Subscriptions page (/my-account/subscriptions/).

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #283
Fixes #194

WC Subscriptions has a user subscriptions cache that is stored in user meta. An example of what this cache looks like is in the screenshot below. 

Screen Shot 2022-11-25 at 9 30 03 am

^ This customer (user ID 1) has 1 subscription with the ID 875. 

This is a persistent cache and not a cache that expires after x time has passed. Because it is persistent, we need to make sure it is updated whenever a subscription is created for a user, or the customer ID of a subscription changes. 

In a WP Posts world, this was done with a series of post update related hooks. eg `added_post_meta`,`update_post_meta`, `deleted_post_meta` etc. When those hooks fire, our `WCS_Post_Meta_Cache_Manager` class checks if it an update, add or delete for a meta-key we're interested in (`_customer_user` or `_subscription_renewal etc), and if it is, it fires an action hook that we listen too and update our caches appropriately. 

These hooks won't fire in HPOS environments with syncing turned off and so our persistent subscription cache falls down. 

This PR adds a new cache manager class to handle HPOS environments and instead of listening on post related hooks, it uses WC CRUD APIs.  

## Description

This PR lays the groundwork for introducing a `WCS_Object_Data_Cache_Manager` which extends the `WCS_Post_Meta_Cache_Manager` class.

Rather than listen on post related hooks, the new `WCS_Object_Data_Cache_Manager` listens on `woocommerce_before_{$this->object_type}_object_save` and `woocommerce_after_{$this->object_type}_object_save` CRUD hooks. 

When an object type (`'order` or `'subscription'`) is saved, this class will see if any meta, or property that it is interested in has changed, and if it has changed, will fire the same hook I mentioned above, and that hook will result in our caches being updated. 

This PR only lays the groundwork, further changes will be needed to handle when an order or subscription is trashed, deleted or untrashed, similar to how the `WCS_Post_Meta_Cache_Manager` works. There aren't equivalent hooks or ways to test this yet because of the following issues: 

- https://github.com/Automattic/woocommerce-subscriptions-core/issues/221
- https://github.com/Automattic/woocommerce-subscriptions-core/issues/195

Once we resolve the subscription trashed/deleted hooks, the new class (`WCS_Object_Data_Cache_Manager`) should add support for them. See issue below.

- https://github.com/Automattic/woocommerce-subscriptions-core/issues/310

## How to test this PR

1. With HPOS enabled and syncing turned off (this change changes nothing on WP Post environments). 
2. Purchase a subscription.
3. Go to the **My account → Subscriptions** page (/my-account/subscriptions/) 
4. Purchase a subscription.
3. Go to the **My account → Subscriptions** page (/my-account/subscriptions/)
    - On `trunk` you won't have both subscriptions listed, only the first subscription will be present.
    - On this branch, all your subscriptions will be listed.

Between testing on `trunk` and this branch, it's best to wipe your site of subscriptions and to delete the cache (see sql query below), so that the testing is consistant (no cache -> cache of 1 -> cache of 2).

| Branch        | Checkouts (2 orders) | My Account → Subscriptions  |
|:------------- |:-----:|:-----:|
| `trunk`     | Screen Shot 2022-11-25 at 11 49 18 am |  Screen Shot 2022-11-25 at 11 51 12 am 🔴  only 1 subscription listed |
| This branch  |  Screen Shot 2022-11-25 at 11 49 18 am  | Screen Shot 2022-11-25 at 11 56 10 am both subscriptions listed 👍 |

## Product impact

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [x]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/data-stores/class-wcs-customer-store-cached-cpt.php [hunk 1]
```diff
@@ -32,19 +31,38 @@ class WCS_Customer_Store_Cached_CPT extends WCS_Customer_Store_CPT implements WC
...
+	 * @param string $name The variable name.
+	 * @return WCS_Post_Meta_Cache_Manager_Many_To_One|WCS_Object_Data_Cache_Manager_Many_To_One Depending on the HPOS environment.
+	 */
+	public function __get( $name ) {
+		if ( 'post_meta_cache_manager' === $name ) {
+			wcs_deprecated_argument( 'WCS_Customer_Store_Cached_CPT::post_meta_cache_manager', '5.2.0', 'WCS_Customer_Store_Cached_CPT::object_data_cache_manager' );
+			return $this->object_data_cache_manager;
+		}
+	}
+
```
Comment (james-allan) [inline includes/data-stores/class-wcs-customer-store-cached-cpt.php:54]: Because I changed the `post_meta_cache_manager` variable to `object_data_cache_manager`, and that variable is `protected`. I've had to deprecate it.

To test this, I've used this code snippet. 


```php
class foo extends WCS_Customer_Store_Cached_CPT {

    public function __construct() {
        $bar = $this->post_meta_cache_manager;
    }
}

new foo();

```


```
PHP Notice:  Function foo::post_meta_cache_manager was called <strong>incorrectly</strong>. foo::post_meta_cache_manager has been deprecated, use foo::object_data_cache_manager instead. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.2.0.)
```

File: includes/data-stores/class-wcs-customer-store-cached-cpt.php [hunk 2]
```diff
@@ -213,7 +233,7 @@ public function set_empty_cache( $user_id ) {
 	 */
 	public function maybe_update_for_post_meta_change( $update_type, $subscription_id, $meta_key, $user_id, $old_user_id = '' ) {
 
-		if ( $this->get_meta_key() !== $meta_key ) {
+		if ( $this->get_meta_key() !== $meta_key && 'customer_id' !== $meta_key ) {
```
Comment (mattallan) [inline includes/data-stores/class-wcs-customer-store-cached-cpt.php]: I'm wondering if we should make changes so that calling `$this->get_meta_key()` returns the meta key we care about i.e. if HPOS is enabled then `$this->get_meta_key()` returns `'customer_id'`.

Not a big deal but I just thought of this when I saw this line.

To do this we'd have to look at changing `meta_key` to protected instead of private and then set it in the constructor

File: includes/class-wcs-post-meta-cache-manager.php [hunk 3]
```diff
@@ -8,7 +8,6 @@
  *
```
Comment (mattallan) [inline includes/class-wcs-post-meta-cache-manager.php:10]: Thoughts on attaching a comment here to mention that this class is only to be used for WP Posts? Reference to where this was brought up: https://github.com/Automattic/woocommerce-subscriptions-core/pull/318#discussion_r1035405101

File: includes/class-wcs-object-data-cache-manager.php [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+		$this->object_type = $object_type;
+		$this->data_keys   = $data_keys;
+	}
+
+	/**
+	 * Attaches callbacks to keep the caches up-to-date.
+	 */
+	public function init() {
+		add_action( "woocommerce_before_{$this->object_type}_object_save", [ $this, 'prepare_object_changes' ] );
+		add_action( "woocommerce_after_{$this->object_type}_object_save", [ $this, 'action_object_cache_changes' ] );
```
Comment (mattallan) [inline includes/class-wcs-object-data-cache-manager.php:67]: I haven't tested this yet but I just wanted to put this question down in GH first before I forget to come back to it 😄 

Question: Do these hooks also get triggered when `save_meta_data()` is called?

i.e.

```
$renewal_order->update_meta_data( '_subscription_renewal', 123 );
$renewal_order->save_meta_data();
```

Comment (mattallan) [reply includes/class-wcs-object-data-cache-manager.php:67]: Based on the nature of this PR having most of the code/functionality behind the HPOS feature flag, I'm wondering if we should treat this PR like a solid base and then open issues for these things separately if they exist?

If that's the case I'm happy to merge this PR as is :)

Comment (james-allan) [reply includes/class-wcs-object-data-cache-manager.php:67]: > Based on the nature of this PR having most of the code/functionality behind the HPOS feature flag, I'm wondering if we should treat this PR like a solid base and then open issues for these things separately if they exist?

Absolutely. There are lots of little things still going on with this PR, like CPT references in class names, post meta mentioned in functions etc. 

I've described working on this PR like pulling on a piece of string, we need to stop somewhere and merging this as a base, safely given it's locked behind HPOS is good with me.

File: includes/data-stores/class-wcs-customer-store-cached-cpt.php (hunk 2 above)
Comment (james-allan) [reply includes/data-stores/class-wcs-customer-store-cached-cpt.php]: I've updated this in [Add function to get the respective data key for the cache manager](https://github.com/Automattic/woocommerce-subscriptions-core/pull/304/commits/d1471f725a55bb029e1ca5c939176d8ec799a1f9). 

As I've mentioned, things are sort of in a halfway state in this class because of the CPT references and post references. There's more work to be done in this area for sure.

**Review by mattallan — APPROVED** [review]
@james-allan the changes added in this PR are looking amazing! I'm happy to approve this and continue iterating on the object cache manager side of this for things like:

 - Support objects being trashed, deleted, untrashed (https://github.com/Automattic/woocommerce-subscriptions-core/issues/310)
 - Update our related post data store classes to use this new object cache manager (needs issue created)

Was there any other changes we need to open issues for?

**Comment by james-allan** [comment]
> Was there any other changes we need to open issues for?

I think once we've got things working fully we should come through an clean these classes up so their names make sense in a HPOS environments. ie make them more generic. I'll file the issues for those two.

**Comment by james-allan** [comment]
To close the loop here, here are the 2 new issues and existing one that were raised out of this PR.

- https://github.com/Automattic/woocommerce-subscriptions-core/issues/339
-  https://github.com/Automattic/woocommerce-subscriptions-core/issues/340
- https://github.com/Automattic/woocommerce-subscriptions-core/issues/310
