### PR TITLE
Fix non-editable subscriptions text

### LINKED ISSUE #665: Explanation text is wrong when subscription text is not editable
## Describe the bug
The [change_order_item_editable_text](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/class-wc-subscriptions-admin.php#L1887-L1900) function is supposed to change the explanatory text when a subscription is not editable. But these texts are not rendered instead the order related texts are displayed on the edit subscription page.

Screenshot 2024-08-28 at 10 14 44 PM

## To Reproduce
- Install a payment plugin that does not support changing subscription amount (this will make the subscription not editable)
- You can use the [Stripe plugin](https://github.com/woocommerce/woocommerce-gateway-stripe/). Remove the `subscription_amount_changes` entry from [here](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/develop/includes/compat/trait-wc-stripe-subscriptions.php#L39).
- As a shopper buy a subscription product.
- Now in your admin dashboard, go to the subscription edit page.
- Notice that the explanation text says `This order is no longer editable.` and the tooltip says `To edit this order change the status back to "Pending"`

### Expected behavior
The texts updated by the [change_order_item_editable_text](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/class-wc-subscriptions-admin.php#L1887-L1900) function should be displayed on the non-editable subscription page.
The text should say `Subscription items can no longer be edited.` and the tooltip should say `This subscription is no longer editable because the payment gateway does not allow modification of recurring amounts.`.

### PR DESCRIPTION
**Pull request by wjrosa**
Fixes #665

## Description

This PR fixes two issues when displaying the "non-editable subscription" text:
- Update the existing method to account for the new label for the pending status (Pending Payment)
- Add support for HPOS tables when identifying the current wp-admin page

## How to test this PR

- Apply this patch to your test environment (by either creating a new release or editing the files directly)
- Follow the [instructions of the original issue](https://github.com/Automattic/woocommerce-subscriptions-core/issues/665) to disable the subscription edit feature
- Confirm that now you can see the text `Subscription items can no longer be edited.`, with the tooltip `This subscription is no longer editable because the payment gateway does not allow modification of recurring amounts.`

## Product impact

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/class-wc-subscriptions-admin.php [hunk 1]
```diff
@@ -2250,4 +2242,30 @@ public static function maybe_keep_variations( $delete_variations, $product, $fro
...
+			return false;
+		}
+
+		if ( wcs_is_custom_order_tables_usage_enabled() ) {
+			$subscriptions_page_id = 'woocommerce_page_wc-orders--shop_subscription';
+		} else {
+			$subscriptions_page_id = 'shop_subscription';
+		}
+
+		return $subscriptions_page_id === $screen->id;
```
Comment (james-allan) [inline includes/admin/class-wc-subscriptions-admin.php]: We can use the `wcs_get_page_screen_id()` helper function here. It will will get the expected screen id for the edit `shop_subscription` screen. 

```suggestion
		return wcs_get_page_screen_id( 'shop_subscription' ) === $screen->id;
```

**Review by james-allan — CHANGES_REQUESTED** [review]
Changes look good. I confirmed that on `trunk` the text is incorrect, but it is correct on this branch. 

| `trunk` | This branch |
|--------|--------|
| Screenshot 2024-09-03 at 1 21 59 PM | Screenshot 2024-09-03 at 1 23 06 PM | 

I just left a small suggestion for a helper function we can use. :)

File: includes/admin/class-wc-subscriptions-admin.php (hunk 1 above)
Comment (wjrosa) [reply includes/admin/class-wc-subscriptions-admin.php]: Oh, that's great to know! Thanks

**Review by james-allan — APPROVED** [review]
Looks good and still tests well after the recent change. 👍
