### PR TITLE
Fix issues with sorting the subscriptions list table on HPOS enabled sites

### LINKED ISSUE #200: With COT no sync, sorting subscriptions by Next Payment and Last Order Date does not give the correct ordering.
> **Warning**
> When HPOS is enabled, this screen will need to be replaced as standard WP screens can not be used with the new Order tables. The Subscriptions listings when HPOS is enabled will now need a controller similar to https://github.com/woocommerce/woocommerce/blob/8fbdbaf3540786deeb4fc7d6b8d57a6b4b5dea6c/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php
> see also #223

## Describe the bug

With custom order table enable but without sync enabled, sorting subscriptions on list admin page by `Next Payment` and `Last Order Date` does not give the correct ordering.

Screen Shot 2022-08-12 at 05 13 06

Screen Shot 2022-08-12 at 05 12 53

Screen Shot 2022-08-12 at 05 12 33

## To Reproduce

1. Install WooCommerce with custom order table feature.
2. Enable custom order table.
3. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > select `Use the WooCommerce orders tables` and uncheck `Keep the posts table and the orders tables synchronized`.
4. Purchase several subscriptions.
5. Go to admin subscriptions list page (wp-admin > WooCommerce > Subscriptions).
6. Click on the column `Next Payment` and `Last Order Date` to order by them ascending and descending.

### Expected behavior

Subscriptions sorted by the selected column in ascending or descending manner accordingly.

### Actual behavior

Subscriptions not sorted the correct way.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes, 4392-gh-woocommerce/woocommerce-subscriptions.
- [x] Does this issue affect WooCommerce Payments? yes, https://github.com/Automattic/woocommerce-payments/issues/4573.

### LINKED ISSUE #471: Subscription List Table does not sort properly with HPOS
## Describe the bug
Sorting subscriptions by clicking on their column headings does not work correctly. Sometimes it has no effect (starting date) sometimes one gets a random order (next payment date).  This is with HPOS enabled, haven't tested recently without but assumed it used to work.

## To Reproduce
Enable HPOS
Go to the active subscriptions list page /?page=wc-orders--shop_subscription&status=wc-active
Sort by "next payment date" notice in the screenshot "in 2 days" shows up in first and fourth position, with "in 6 days" and "July 26th" in between the two.

Click on the "Start Date" heading, and nothing at all seems to happen. It does not sort, nor does it reverse/descending sort after repeated clicks.

### Expected behavior
Clicking on column headers should sort correctly when HPOS is enabled.

### Actual behavior
Clicking on column headers is either doing nothing, sorting on the wrong column, or sorting completely incorrectly.

## Product impact
Impossible to clearly see which subscriptions need attention.

- [yes] Does this issue affect WooCommerce Subscriptions?

CleanShot 2023-07-14 at 10 57 33@2x

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #200 
Fixes #471 

## Description

On HPOS enabled sites, filtering the subscriptions list table by the subscription's next payment, start, end, trial end, or last payment date all failed to correctly sort the table. 

This originally required changes to WC core to fix, however with https://github.com/woocommerce/woocommerce/pull/36403 merged and released for some time, ordering the list table by meta value is now possible. 

This PR makes use of those changes in WC to make sure we format the meta query args to ensure the list table is sorted by those meta values. Specially making sure we set the `meta_key` and `meta_value` order by properties. 

eg: 

```php
array (
    ['limit'] => 20
    ['page'] => 1
    ['paginate'] => 1
    ['type'] => 'shop_subscription'
    ['orderby'] => 'meta_value' // <-- 
    ['order'] => 'DESC'
    ['meta_key'] => '_schedule_next_payment' // <--
)
```

## How to test this PR

1. Enable HPOS if it's not already enabled.
2. Purchase a couple of subscriptions with various properties, end dates, varying next payment dates.
3. Go to the admin subscriptions list table and order the list table by any of the columns.
   - eg next payment dates, end dates, last payment dates.
4. On `trunk` you'll notice the table isn't correctly ordered.
5. On this branch all ordering should work as expected. 

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/class-wcs-admin-post-types.php [hunk 1]
```diff
@@ -1752,4 +1782,109 @@ public function print_bulk_actions_script() {
...
+			ON {$order_table}.id = lp.meta_value
+			LEFT JOIN {$order_table} orders on {$order_table}.parent_order_id = orders.ID";
+
+		return $pieces;
+	}
+
+	/**
+	 * Adds Order table query clauses to order the subscriptions list table by last payment date.
+	 *
+	 * This function is the high performance method and is a HPOS version of @see self::orders_table_clauses_high_performance().
```
Comment (Mayisha) [inline includes/admin/class-wcs-admin-post-types.php]:
```suggestion
	 * This function is the high performance method and is a HPOS version of @see self::posts_clauses_high_performance().
```

File: includes/admin/class-wcs-admin-post-types.php [hunk 2]
```diff
@@ -1752,4 +1782,109 @@ public function print_bulk_actions_script() {
...
 	}
+
+	/**
+	 * Adds Order table query clauses to order the subscriptions list table by last payment date.
+	 *
+	 * There are 2 methods we use to order the subscriptions list table by last payment date:
+	 *  - High performance: This method uses a temporary table to store the last payment date for each subscription.
+	 *  - Low performance: This method uses a subquery to get the last payment date for each subscription.
+	 *
+	 * This function is the lower performance method and is a HPOS version of @see self::posts_clauses_low_performance().
```
Comment (Mayisha) [inline includes/admin/class-wcs-admin-post-types.php]: This part of the comment seems a bit confusing.

**Review by Mayisha — APPROVED** [review]
Thanks @james-allan. :tada: 
I can now sort the subscription table perfectly by different date attributes. :+1: 
I have compared the queries with the existing non HPOS ones and here it seems to be doing the same thing in HPOS way. :+1: 
The fix is working as described. I was a bit confused by a couple of comments that I have commented below. :smiley:

File: includes/admin/class-wcs-admin-post-types.php (hunk 2 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-post-types.php]: Opps, that wasn't supposed to be there. 😅 I've removed that in https://github.com/Automattic/woocommerce-subscriptions-core/pull/546/commits/bcf0f6a2be9a41786c50102c01f799d4b03c517d and tidied up these function comments in https://github.com/Automattic/woocommerce-subscriptions-core/pull/546/commits/b92f2315a84cd2223597fb9857f5159b4b74ff3a.

**Comment by james-allan** [comment]
Thanks for the review @Mayisha. I've fixed those issues. 😄
