### PR TITLE
Always attach our Checkout Blocks integration to fix issues when Subscriptions is loaded before WooCommerce

### LINKED ISSUE #486: Subscriptions Checkout Blocks integration not loading
## Describe the bug

With WooCommerce + Subscriptions + Stripe or Square, using the checkout block is not properly showing the subscription recurring totals on the checkout and are instead being rendered as simple/single products.

image

This issue is caused by the WC Subscriptions extension being inited before WooCommerce Core has loaded causing this [block of code](https://github.com/Automattic/woocommerce-subscriptions-core/blob/507720f600363a6c1e7da1b4b82660c7ab6a0c0e/includes/class-wc-subscriptions-core-plugin.php#L156-L160) to never run because the `Automattic\WooCommerce\Blocks` doesn't exist yet.

## To Reproduce

1. Activate WC 7.9, Subscriptions 5.3.1 & Square or Stripe
2. Create a new checkout page using checkout blocks
3. Add a subscription product to your cart
4. Notice in the Order Summary section the cart item prices are not showing as recurring totals

### Expected behavior

image

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

This bug does not affect WooPayments as the checkout block class exists at the time of initing subscriptions core.

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #486 

## Description

There's an issue where the Checkout Block is not properly showing the subscription recurring totals on the checkout and are instead being rendered as simple/single prices.

image

After some investigation, I found out this was being caused by our Checkout Blocks support code never being attached because at the time of initing WC Subscriptions, the `Automattic\WooCommerce\Blocks\Package` class doesn't exist yet.

To fix this, I've made sure we're always attaching our `woocommerce_blocks_loaded` code and then moved our version checks to happen inside those callbacks.

## How to test this PR

1. Activate WooCommerce 7.9, Subscriptions 5.3.1 & the latest Stripe
2. Add a Checkout Block page
3. Add a subscription product to your cart
4. On `trunk` you'll see a non-recurring total on the checkout
image
5. On this branch you should see the correct recurring totals:
image

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wc-subscriptions-core-plugin.php [hunk 1]
```diff
@@ -153,11 +153,9 @@ public function init() {
 		// Initialise the cache.
 		$this->cache = WCS_Cache_Manager::get_instance();
 
-		if ( class_exists( 'Automattic\WooCommerce\Blocks\Package' ) && version_compare( \Automattic\WooCommerce\Blocks\Package::get_version(), '4.4.0', '>' ) ) {
-			// When WooCommerceBlocks is loaded, set up the Integration class.
-			add_action( 'woocommerce_blocks_loaded', array( $this, 'setup_blocks_integration' ) );
-			add_action( 'woocommerce_blocks_loaded', array( 'WC_Subscriptions_Extend_Store_Endpoint', 'init' ) );
-		}
+		// When WooCommerceBlocks is loaded, set up the Integration class.
+		add_action( 'woocommerce_blocks_loaded', array( $this, 'setup_blocks_integration' ) );
```
Comment (mattallan) [inline includes/class-wc-subscriptions-core-plugin.php:157]: I thought about consolidating these callbacks to just the one `setup_blocks_integration()` function

Then inside that function we can manually call `WC_Subscriptions_Extend_Store_Endpoint::init()` to replace the hook we just removed.

I avoided going with this approach as it technically breaks backward compatibility in but in a very minor way (e.g. a 3pd may have been unhooking our functionality)

**Review by james-allan — APPROVED** [review]
Changes look good to me and work well. 
Just noting that I've submitted a change log entry.
