### PR TITLE
[HPOS] Update the subscription address when a customer changes their address while paying for a renewal order

### LINKED ISSUE #412: [HPOS] Changing addresses while paying for a renewal order doesn't update the subscription's address when HPOS is enabled
## Describe the bug

When you pay for a renewal order via the checkout and change your address, the address on the subscription is not updated when HPOS is enabled.

This issue is caused by our `WCS_Cart_Renewal::maybe_update_subscription_address_data()` and `WCS_Cart_Renewal::maybe_update_subscription_address_data_from_store_api()` functions using the legacy order function [`set_address()`](https://github.com/woocommerce/woocommerce/blob/21c4edf4e219d2cce19466c772bc3d53c384cc38/plugins/woocommerce/includes/legacy/abstract-wc-legacy-order.php#L334) which calls both `update_post_meta()` and the CRUD setter, but doesn't call `$save()`.

```
public function set_address( $address, $type = 'billing' ) {
	foreach ( $address as $key => $value ) {
		update_post_meta( $this->get_id(), "_{$type}_" . $key, $value );
		if ( is_callable( array( $this, "set_{$type}_{$key}" ) ) ) {
			$this->{"set_{$type}_{$key}"}( $value );
		}
	}
}
```

In a HPOS environment this functions differently to what how we intended to use it and doesn't actually write the address changes to the database. Issues with us using this function in a HPOS environment:

1. This function always calls `update_post_meta()` which means when is HPOS enabled and syncing is turned off, we're always writing these addresses straight to the `shop_order_placehold` post object. This isn't ideal because we should always rely on the WC Core data synchronizer to write to the postmeta table when necessary
2. This function also doesn't save changes the DB when HPOS is enabled so we need to make sure the `set_address()` call is followed by a `save()`.

## To Reproduce

1. Purchase a subscription with HPOS enabled
2. On the Edit subscription page, use the actions to "Create a pending renewal order"
3. From the My Account > View Subscription, click on the Pay button next to the latest renewal
4. While paying for the renewal order, change your billing/shipping address
5. After completing the checkout visit the Edit Subscription page and confirm the address on the subscription has not been updated :x:
6. Go into the database and search the subscription ID in the `wp_postmeta` table and notice the address changes were incorrectly saved to these old tables. ❌ 

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #412 

## Description

With HPOS enabled, when a customer is paying for a renewal order and updates their address on the checkout, the subscription doesn't get updated with the newest address.

This is because we were using a legacy order function `$subscription->set_address()` which calls both `update_post_meta()` and the CRUD method to set the address prop, but we were never saving the subscription.

There are two issues with our code using `set_address()`:
1. This function always calls `update_post_meta()` which shouldn't be used in an HPOS environment. When HPOS is enabled and data syncing disabled, the address was always being saved to the `shop_order_placehold` post object.
2. Address data wasn't being saved on the subscription because we weren't calling `$subscription->save()`

This PR address both of these issues by refactoring how we were using `$subscription->set_address()`.

- Inside `maybe_update_subscription_address_data()` we were already setting up arrays of shipping and billing data so I changed this function to use the `set_shipping|billing_$field()` functions and then call `$subscription->save()`.
- Inside `maybe_update_subscription_address_data_from_store_api()` we are already given the arrays of address data so I opted to use the new WC Core functions introduced in WC 7.1 which accepts an address array and sets the data

## How to test this PR

Testing these changes requires testing both the Checkout Block and old checkout flows and with HPOS enabled and disabled.

1. Purchase a subscription
2. On the Edit Subscription page use the action list to **Create pending renewal order**
3. Go to My Account > View Subscription and click to pay for the pending order
4. While on the checkout, change your address and submit the checkout
5. Check that the address on the subscription has been updated
6. When HPOS is enabled with syncing off, confirm the address data is no longer being saved in postmeta.
7. Perform the same checks for HPOS disabled/enabled and with Checkout Blocks.

## Product impact

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wcs-cart-renewal.php [hunk 1]
```diff
@@ -1159,22 +1159,27 @@ public function maybe_update_subscription_address_data( $customer_id, $checkout_
 		$cart_renewal_item = $this->cart_contains();
 
 		if ( false !== $cart_renewal_item ) {
-			$subscription    = wcs_get_subscription( $cart_renewal_item[ $this->cart_item_key ]['subscription_id'] );
-			$billing_address = $shipping_address = array();
-			foreach ( array( 'billing', 'shipping' ) as $address_type ) {
+			$subscription         = wcs_get_subscription( $cart_renewal_item[ $this->cart_item_key ]['subscription_id'] );
+			$subscription_updated = false;
+			$billing_address      = [];
+			$shipping_address     = [];
```
Comment (Jinksi) [inline includes/class-wcs-cart-renewal.php]: Nit: these vars are now unused and can be removed.

Screenshot 2023-03-07 at 13 54 48

**Review by Jinksi — APPROVED** [review]
This LGTM @mattallan 🙌 

I've tested the following (WC 7.4.1):

Pay for renewal order as a customer, updating Billing and Shipping address at checkout.

- [x] HPOS disabled. `wp_postmeta` table is updated with the correct value.
- [x] HPOS enabled (no-sync). `wp_wc_orders_meta` is updated with the correct values. `wp_postmeta` table is not modified.

File: includes/class-wcs-cart-renewal.php (hunk 1 above)
Comment (mattallan) [reply includes/class-wcs-cart-renewal.php]: nice nit! 💃 I'll get that fixed up

**Comment by mattallan** [comment]
Thanks @Jinksi, I've removed those unused variables in [b39bf6e](https://github.com/Automattic/woocommerce-subscriptions-core/pull/413/commits/b39bf6ecac66530057debd52fec8119888b8b678). Merging this :shipit:
