### PR TITLE
Fixes error on Admin Edit Subscription page when the subscription has custom billing fields.

### LINKED ISSUE #401: Missing is_callable() check during output of shipping/billing address in subscription meta box
## Describe the bug
In the [WCS_Meta_Box_Subscription_Data](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php#L216) class for each billing (and shipping) field the value is obtained the following way:

`$field['value'] = $subscription->{"get_billing_$key"}();`

and 

`$field['value'] = $subscription->{"get_shipping_$key"}();`

This will result in a fatal error for custom shipping/billing fields added by third party developers. That's why the `is_callable()` check is added in the same file while constructing the address display values, e.g.:

```php
$function_name = 'get_billing_' . $key;

if ( is_callable( array( $subscription, $function_name ) ) ) {
    $field_value = $subscription->$function_name( 'edit' );
} else {
    $field_value = $subscription->get_meta( '_billing_' . $key );
}
```

The same check is needed for line [216](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php#L216) and [306](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php#L306). This is a serious bug which will lead to many user complaints.

## To Reproduce
Register a custom shipping field:

```php
add_filter( 'woocommerce_admin_billing_fields', function( $fields ) {
	$fields['my_custom_field'] = array(
		'label' => 'My custom field'
	);

	return $fields;
}, 0 );
```
Navigate to WooCommerce > Subscriptions and select a subscription - fatal error occurs.

### Expected behavior
Use `is_callable()` before calling order/subscription methods.

## Product impact
- [x] Does this issue affect WooCommerce Subscriptions?

### LINKED ISSUE #402: Fatal error with custom admin billing fields
## Describe the bug
When a site uses custom address fields added with `woocommerce_admin_billing_fields` or `woocommerce_admin_shipping_fields`, opening a subscription in the admin will result in a call to undefined method error.

It appears that the dynamic function call based on the keys in the billing and shipping addresses is failing because there are no methods to match the non-default fields.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/d37bd4db47ccaf156fc57b4dc61761f9ab56d686/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php#L216

## To Reproduce
1.  Insert a custom billing or shipping field to the admin order screen. Here's the example I used:

```
add_filter( 'woocommerce_admin_billing_fields', 'ijag_add_billing_field' );
function ijag_add_billing_field( $fields ) {
	
	$fields[ 'lucky_day' ]   = array(
		'label'        => 'Lucky Day',
		'required'     => true,
		'class'        => array( 'form-row-wide' ),
		'priority'     => 20,
		'placeholder'  => 'Is today your lucky day?',
	);
	
	return $fields;
}
```
2.  Go to WooCommerce > Subscriptions and click on any subscription.
3. Observe the page doesn't finish loading.

### Expected behavior
I expect to be able to load the edit subscription screen with custom fields.

### Actual behavior
This error will be triggered instead of completely loading the page:

```
Uncaught Error: Call to undefined method WC_Subscription::get_billing_lucky_day() in /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php:216 Stack trace: #0 /wordpress/core/6.1.1/wp-admin/includes/template.php(1409): WCS_Meta_Box_Subscription_Data::output(Object(WC_Subscription), Array) #1 /wordpress/core/6.1.1/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post)) #2 /wordpress/core/6.1.1/wp-admin/post.php(206): require('/wordpress/core...') #3 {main} thrown in /srv/htdocs/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php on line 216
```

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

## Additional context
5914186-zd-woothemes

<details>
`
### WordPress Environment ###

WordPress address (URL): https://pookiefly.com
Site address (URL): https://pookiefly.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.1.14
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.86.0
OpenSSL/1.1.1n

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.3.0
WC Database Prefix: wp_
Total Database Size: 101.07MB
Database Data Size: 80.03MB
Database Index Size: 21.04MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 2.02MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.25MB + Index: 0.25MB + Engine InnoDB
vp_backup_wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_lhr_log: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_options: Data: 1.52MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 2.52MB + Index: 1.94MB + Engine InnoDB
vp_backup_wp_posts: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
vp_backup_wp_snippets: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
vp_backup_wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_exported_csv_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
vp_backup_wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_flat_rate_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
vp_backup_wp_wps_index: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wps_object_term: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_lhr_log: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_bounces: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_agents: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 5.05MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 1.98MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_snippets: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_mnm_child_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_products: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wc_product_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_attribute_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_downloads: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_product_relationships: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_variation_attribute_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gc_cardsmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_wps_index: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_object_term: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 0.19MB + Index: 0.19MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
__wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.22MB + Index: 0.22MB + Engine InnoDB
__wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
__wp_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_lhr_log: Data: 11.52MB + Index: 0.00MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_options: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
__wp_postmeta: Data: 2.52MB + Index: 1.91MB + Engine InnoDB
__wp_posts: Data: 1.52MB + Index: 0.13MB + Engine InnoDB
__wp_snippets: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_bundle_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_composite_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_exported_csv_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_gc_activity: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_gc_cards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
__wp_wps_hit: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
__wp_wps_index: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
__wp_wps_key: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wps_object_term: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
__wp_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
__wp_wps_query: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wps_uri: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wp_phpmyadmin_extension__errors_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 84
aw_workflow: 5
custom_css: 1
global_product_addon: 1
mailpoet_page: 1
nav_menu_item: 7
option-tree: 1
order_shipment: 4
page: 27
post: 2
product: 82
product_variation: 38
revision: 124
shipping_package: 1
shop_coupon: 15
shop_order: 332
shop_order_refund: 23
shop_subscription: 19
wafs: 1
wc_membership_plan: 1
wc_pickup_location: 1
wc_user_membership: 1
wcpf_item: 2
wcpf_project: 1
wp_global_styles: 1
wp-rest-api-log: 23

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Code Snippets: by Code Snippets Pro – 3.2.2
WooCommerce Stripe Gateway: by WooCommerce – 7.0.1
WooCommerce Payments: by Automattic – 5.3.0
WooCommerce Subscriptions: by WooCommerce – 4.8.0
WooCommerce: by Automattic – 7.3.0

### Inactive Plugins (26) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Custom Currency Symbol for WooCommerce: by Bill Robbins – 1.0.0
Jetpack: by Automattic – 11.8-a.13
JSM's Show Post Metadata: by JS Morisset – 3.0.9
Log HTTP Requests: by FacetWP
LLC – 1.4

Passwordless Login: by Cozmoslabs
sareiodata – 1.1.1

Query Monitor: by John Blackbourn – 3.11.1
Query Monitor Extend: by Caleb Stauffer – 1.0
Rapid Products for WooCommerce: by Bill Robbins – 0.2
Rapid Products for WooCommerce: by Bill Robbins – 0.2
Stock Update Logger: by Hiro – 0.1b
Temporary Login Without Password: by StoreApps – 1.7.3
User Role Editor: by Vladimir Garagulya – 4.63.2
User Switching: by John Blackbourn & contributors – 1.7.0
WC Shop Title: by Bill Robbins – 1.0.0
WCS staging: by mb – 1.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.3.2
WooCommerce Action Logging: by Bill Robbins – 0.0
WooCommerce Beta Tester: by WooCommerce – 2.1.0
WooCommerce Blocks: by Automattic – 9.4.1
WooCommerce Product Tables Feature Plugin: by Automattic – 1.0.0-dev
WooCommerce Shipping & Tax: by WooCommerce – 2.2.1
WooCommerce Smooth Generator: by Automattic – 1.0.1
WP Debugging: by Andy Fragen – 2.11.17
WP Mail Logging: by SendLayer – 1.10.5
WP phpMyAdmin: by Puvox.software – 5.2.0.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #114 - /communication-preferences/

### Theme ###

Name: Storefront
Version: 4.2.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://pookiefly.com
Subscriptions-core Library Version: 5.3.0
Subscription Statuses: wc-active: 2
wc-on-hold: 4
wc-cancelled: 13

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Illinois

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 2
wc-cancelled: 12
wc-on-hold: 4

### Payment Gateway Support ###

Cash on delivery: products
WooCommerce Payments: products
refunds
multiple_subscriptions
subscription_cancellation
subscription_payment_method_change_admin
subscription_payment_method_change_customer
subscription_payment_method_change
subscription_reactivation
subscription_suspension
subscriptions
subscription_amount_changes
subscription_date_changes
tokenization
add_payment_method

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-31 23:09:35 -06:00
Options: ✔
Notes: 86
Onboarding: completed

### WooCommerce Payments ###

Version: 5.3.0
Connected to WPCOM: Yes
Blog ID: 173365859
Account ID: acct_1G9axHGAccZ7MjSw

### Action Scheduler ###

Complete: 188
Oldest: 2022-12-31 21:20:06 -0600
Newest: 2023-01-31 12:03:51 -0600

Pending: 3
Oldest: 2023-01-31 12:07:26 -0600
Newest: 2023-02-01 08:13:37 -0600

### Status report information ###

Generated at: 2023-01-31 12:07:37 -06:00
`
</details>
-->

### PR DESCRIPTION
**Pull request by mattallan**
Fixes #401
Fixes #402
Fixes https://github.com/woocommerce/woocommerce-subscriptions/issues/4468

## Description

When a store has set custom address fields (using `woocommerce_admin_billing_fields` or `woocommerce_admin_shipping_fields`) and these fields don't have `$order->get_billing_{field}` or `$order->get_shipping_{field}` functions, opening the Edit subscription page in the admin will result in:

```
[31-Jan-2023 23:21:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WC_Subscription::get_billing_my_custom_field() in /Users/matt/local/woo/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php:216
Stack trace:
#0 /Users/matt/local/woo/wp-admin/includes/template.php(1401): WCS_Meta_Box_Subscription_Data::output(Object(WC_Subscription), Array)
#1 /Users/matt/local/woo/wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#2 /Users/matt/local/woo/wp-admin/post.php(206): require('/Users/matt/loc...')
#3 /Users/matt/.composer/vendor/laravel/valet/server.php(235): require('/Users/matt/loc...')
#4 {main}
  thrown in /Users/matt/local/woo/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php on line 216
```

To fix this problem, we just need to make sure the function exists before we try to use it 😅 In cases where a getter function doesn't exist, we need to fallback to using `$subscription->get_meta( '_custom_meta_key' )` 

## How to test this PR

This issue was reported by a store using our EU Vat number plugin, however it can also be replicated by using the following snippet to add custom billing and shipping fields:

```
add_filter( 'woocommerce_admin_billing_fields', function( $fields ) {
	$fields['my_custom_field'] = array(
		'label' => 'My custom field'
	);

	return $fields;
}, 0 );

add_filter( 'woocommerce_admin_shipping_fields', function( $fields ) {
	$fields['my_custom_field'] = array(
		'label' => 'My custom field'
	);

	return $fields;
}, 0 );
```

1. With this snippet, on `trunk`, try to navigate to the Edit Subscription page. You will notice half the page loaded and a fatal error.
2. Check out this branch and confirm there's no fatal error.

## Product impact

- [x] Added changelog entry (or does not apply)
- [x] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php [hunk 1]
```diff
@@ -213,7 +213,12 @@ public static function output( $subscription ) {
 									wcs_woocommerce_wp_select( $field, $subscription );
 									break;
 								default:
-									$field['value'] = $subscription->{"get_billing_$key"}();
+									if ( is_callable( array( $subscription, 'get_billing_' . $key ) ) ) {
+										$field['value'] = $subscription->{"get_billing_$key"}();
+									} else {
+										$field['value'] = $subscription->get_meta( '_billing_' . $key );
```
Comment (mattallan) [inline includes/admin/meta-boxes/class-wcs-meta-box-subscription-data.php]:
```suggestion
										$field['value'] = $subscription->get_meta( $field['id'] );
```

**Comment by Jinksi** [comment]
Will this resolve WCS issue https://github.com/woocommerce/woocommerce-subscriptions/issues/4468?

I'm attempting to test with https://github.com/woocommerce/woocommerce-eu-vat-number but I am seeing another fatal (unrelated I believe):

```
Fatal error: Uncaught Error: Call to undefined function wc_eu_vat_get_vat_from_order()
in [/var/www/html/wp-content/plugins/woocommerce-eu-vat-number/includes/class-wc-eu-vat-number.php](vscode://file/%2Fvar%2Fwww%2Fhtml%2Fwp-content%2Fplugins%2Fwoocommerce-eu-vat-number%2Fincludes%2Fclass-wc-eu-vat-number.php:568) on line 568
```

**Update:** It is unrelated:


```
WooCommerce EU VAT Number is inactive. Your server does not provide SOAP support which is required functionality for communicating with VIES. You will need to reach out to your web hosting provider to get information on how to enable this functionality on your server.
```

**Comment by mattallan** [comment]
@Jinksi yeah it will fix EU Vat Number which is using the [`woocommerce_admin_billing_fields`](https://github.com/woocommerce/woocommerce-eu-vat-number/blob/2143aa2dff3818571d7569f844fe1688b57b924d/includes/class-wc-eu-vat-admin.php#L29) filter.

**Review by Jinksi — APPROVED** [review]
LGTM @mattallan 🏆 

I've tested by using snippets from the description (with WCPay standalone and WCPay + WCS).
* On `trunk`, I see the error when loading the Edit Subscription screen.
* On this branch, the Edit Subscription screen loads correctly and I can edit the custom billing/shipping fields and view the stored value.
