### PR TITLE
[HPOS] Refactor `wcs_is_subscription` helper function to support HPOS

### LINKED ISSUE #288: [HPOS] Replace `get_post_type()` with WC_Data_Store::load( 'subscription' )->get_order_type( $id )
## Describe the bug

To support subscriptions stored in different data stores, we need to replace all cases of `get_post_type()` with `WC_Data_Store::load( 'subscription' )->get_order_type( $id )`.

Doing a search of `get_post_type(` in `subscriptions-core` code there's 15 instances of this still being used.

In #153 we only targetted code which used this function on WC Orders, but as part of tackling this issue we should replace all cases.

---

#### Updating `get_post_type( $subscription_id )`

```
'shop_subscription' == get_post_type( $post_id )
```

Replace with:

```
'shop_subscription' === WC_Data_Store::load( 'subscription' )->get_order_type( $id )
```

#### Updating `get_post_type( $product_id )`

I could only find one instance where we're using `get_post_type()` with product ID inside `user_can_not_delete_subscription()`

```
0 === strpos( get_post_type( $args[2] ), 'product' )
```

The issue with`WC_Data_Store::load( 'product' )->get_product_type( $id )` is that it formats product types i.e. `'product_variation'` is returned as just `'variation'` so there's not a simple one-to-one replacement for this one.

We can probably just ignore this one case for now.

### PR DESCRIPTION
**Pull request by Jinksi**
Partially fixes #288

## Description

This PR refactors the `wcs_is_subscription` helper function to support HPOS-enabled stores by replacing the usage of `get_post_type()` with `WC_Data_Store::load( 'subscription' )->get_order_type( $subscription )`.

## How to test this PR

1. Ensure PHP unit tests pass. ([See test for `wcs_is_subscription`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/f8d92df04d61d1e313f7020bc43d1eb629dfc4fe/tests/unit/test-wcs-functions.php#L61-L93) which covers various argument types)
2. This function is used in various places throughout subs-core. Therefore basic smoke-testing is encouraged with HPOS enabled & disabled.

We should lean on our intended pre-release testing of critical flows for broadly-impactful changes such as this.

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [x]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0) **Not applicable**

### CODE REVIEW

File: wcs-functions.php [hunk 1]
```diff
@@ -30,16 +30,18 @@
 
 /**
  * Check if a given object is a WC_Subscription (or child class of WC_Subscription), or if a given ID
- * belongs to a post with the subscription post type ('shop_subscription')
+ * belongs to a post with the subscription post type ('shop_subscription').
```
Comment (shendy-a8c) [inline wcs-functions.php]: When HPOS is enabled, this is not true right? I suggest a change. Feel free to modify.

```suggestion
 * belongs to a post or order with type ('shop_subscription').
```

File: wcs-functions.php [hunk 2]
```diff
@@ -30,16 +30,18 @@
...
  *
  * @since  1.0.0 - Migrated from WooCommerce Subscriptions v2.0
+ *
+ * @param mixed $subscription A WC_Subscription object or post ID
```
Comment (shendy-a8c) [inline wcs-functions.php]: Again, here so that we are not fixated to post only. Feel free to modify.

```suggestion
 * @param mixed $subscription A WC_Subscription object or an ID.
```

File: wcs-functions.php [hunk 3]
```diff
@@ -30,16 +30,18 @@
...
  * @return boolean true if anything is found
  */
 function wcs_is_subscription( $subscription ) {
 
 	if ( is_object( $subscription ) && is_a( $subscription, 'WC_Subscription' ) ) {
 		$is_subscription = true;
-	} elseif ( is_numeric( $subscription ) && 'shop_subscription' == get_post_type( $subscription ) ) {
+	} elseif ( is_numeric( $subscription ) && 'shop_subscription' === WC_Data_Store::load( 'subscription' )->get_order_type( $subscription ) ) {
```
Comment (shendy-a8c) [inline wcs-functions.php:44]: Thinking out loud here. Is there any chance `WC_Data_Store` isn't defined or `WC_Data_Store::load( 'subscription' )` is not an object resulting a fatal error? I can't think of any.

**Review by shendy-a8c — APPROVED** [review]
Looks good. I tested using [WP Console](https://wordpress.org/plugins/wp-console/) and passed id of a non-subscription, a subscription, with HPOS enabled, disabled, and varying HPOS settings (order table and sync).

I have minor suggestions on the comment wording.

File: wcs-functions.php (hunk 3 above)
Comment (Jinksi) [reply wcs-functions.php:44]: 👍  I don't think so, as long as the `WCS_Orders_Table_Data_Store_Controller()` has been instantiated, which happens early in the `WC_Subscriptions_Core_Plugin` constructor.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/9e0566089006283af18a70d6326252e5cc0b7219/includes/class-wc-subscriptions-core-plugin.php#L61
