### PR TITLE
Display related orders table when viewing the new "Edit Order" page (HPOS enabled stores)

### LINKED ISSUE #192: Related Orders table not displayed when viewing new Edit Order page (COT enabled stores)
## Describe the bug

When COT is enabled, the related-order table is not shown when viewing the Edit Order page for subscription orders.

image

I haven't done much digging into this but something I noticed is when COT is enabled, the view order URL changes from the edit post url to a new admin url:

Old : `/wp-admin/post.php?post=1360&action=edit`
New: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`

I've opened an issue to address the URL issue: https://github.com/Automattic/woocommerce-subscriptions-core/issues/193

## To Reproduce

1. Enable the COT feature and turn on COT ([see guide here](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#easy-way))
2. Go into **WooCommerce > Settings > Advanced > Custom Data Stores**
3. Make sure "Use the WooCommerce orders tables" is enabled
4. Purchase a subscription and note the order ID
5. From WP admin dashboard, go to **WooCommerce > Orders** and view the new order
6. Notice there's no related orders table

### Expected behavior

Parent orders and renewal orders have a related orders table with details about all subscription related order.

image

### Actual behavior

Related orders table isn't loaded.
When Custom order tables

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #192 

## Description

This PR displays the related orders table meta box on the "Edit Order" and "Edit Subscription" when HPOS is enabled with non-HPOS compatibility.

In addition:
- [x] PHPCS formatting has been fixed in related files.
	(mostly moved to #280)
- [x] PHPCS errors/warnings have been addressed in related files.
	(mostly moved to #280)
	- Some low-hanging errors/warnings have been addressed.
- [x] Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0) - yes, 3 hooks added

## How to test this PR

1. Enable the COT feature and turn on COT ([see guide here](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#easy-way)).
2. Go into **WooCommerce > Settings > Advanced > Custom Data Stores**.
3. Make sure "Use the WooCommerce orders tables" is enabled.
4. Purchase a subscription and note the order ID.
5. From WP admin dashboard, go to **WooCommerce > Orders** and view the "Edit Order" page for the order ID noted above.
6. Notice that the Related Orders table meta box is visible and contains a link to the related Subscription.
   You should not see the current order within this table.
	Screenshot 2022-11-08 at 12 57 37	
7. Click on the related Subscription to be taken to the "Edit Subscription" page.
   You should not see the current subscription within this table.
	Screenshot 2022-11-08 at 12 57 24
9. Notice that the Related Orders table meta box is visible and contains a link to the parent order.
10. Clicking on the parent order will take you to the "Edit Order" page as above.

Recommended compatibility tests (checked = tested by PR author):
- [x] WCPay
- [x] WC Subs
	- [x] with WC Subs activated + HPOS enabled + syncing on, ~the Related Orders table isn't rendered correctly and following PHP Notice occurs~ it uses a newly deprecated hook. Need to update this issue to clarify:
	https://github.com/woocommerce/woocommerce-subscriptions/issues/4417
- [x] WC 6.8.0 – toggling between this subs-core branch & `trunk` results in identical output.
- [x] WC HPOS enabled + syncing off
- [x] WC HPOS enabled + syncing on
- [x] WC HPOS disabled

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref

### CODE REVIEW

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 1]
```diff
@@ -85,8 +87,12 @@ public function add_meta_boxes() {
 		add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_subscription', 'normal', 'low' );
 
 		// Only display the meta box if an order relates to a subscription
-		if ( 'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $post_ID ) && wcs_order_contains_subscription( $post_ID, 'any' ) ) {
-			add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_order', 'normal', 'low' );
+		if ( wcs_order_contains_subscription( $post_or_order_object, 'any' ) ) {
+			// If HPOS is enabled, we need to get the screen id and provide it to add_meta_box().
+			$screen = wc_get_container()->get( CustomOrdersTableController::class )->custom_orders_table_usage_is_enabled()
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-meta-boxes.php]: We have a helper function for this now: `wcs_is_custom_order_tables_usage_enabled()`

Comment (mattallan) [reply includes/admin/class-wcs-admin-meta-boxes.php]: This will resolve any issues on older versions of WC where `CustomOrdersTableController` doesn't exist.

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Nice! I knew that line would break spectacularly when I tested backwards-compat but didn't want to wrap it in yet another if/ternary 😂

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Resolved in 195a29e

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 2]
```diff
@@ -112,36 +113,44 @@ public function remove_meta_box_save( $post_id, $post ) {
 	 */
 	public function enqueue_styles_scripts() {
 		global $post;
+		$ver = WC_Subscriptions_Core_Plugin::instance()->get_plugin_version();
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php]: This allows browser-cached scripts to be refreshed when this version number is updated.

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 3]
```diff
@@ -112,36 +113,44 @@ public function remove_meta_box_save( $post_id, $post ) {
...
 
 		// Get admin screen id
 		$screen    = get_current_screen();
 		$screen_id = isset( $screen->id ) ? $screen->id : '';
 
 		if ( 'shop_subscription' == $screen_id ) {
 
-			wp_register_script( 'jstz', WC_Subscriptions_Core_Plugin::instance()->get_subscriptions_core_directory_url( 'assets/js/admin/jstz.min.js' ) );
+			wp_register_script( 'jstz', WC_Subscriptions_Core_Plugin::instance()->get_subscriptions_core_directory_url( 'assets/js/admin/jstz.min.js' ), [], $ver, false );
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php]: Passing `$in_footer` as `false` to match current (default) enqueue behaviour.

File: includes/admin/meta-boxes/views/html-related-orders-row.php [hunk 4]
```diff
@@ -11,52 +11,52 @@
 ?>
 <tr>
 	<td>
-		<a href="<?php echo esc_url( get_edit_post_link( $order->get_id() ) ); ?>">
+		<a href="<?php echo esc_url( get_edit_post_link( $row_order->get_id() ) ); ?>">
```
Comment (Jinksi) [inline includes/admin/meta-boxes/views/html-related-orders-row.php]: Changed to `$row_order` to remove confusion between the global/current order and related orders in each row.

File: includes/admin/class-wc-subscriptions-admin.php [hunk 5]
```diff
@@ -1203,29 +1214,32 @@ public static function has_settings() {
 	 */
 	public static function get_settings() {
 
-		return apply_filters( 'woocommerce_subscription_settings', array(
-
+		return apply_filters(
```
Comment (james-allan) [inline includes/admin/class-wc-subscriptions-admin.php:1222]:
```suggestion
		/**
		 * Filter the settings for the Subscriptions extension.
		 *
		 * @param array $settings Array of settings in the format required by the woocommerce_admin_fields() function.
		 */
		return apply_filters( 'woocommerce_subscription_settings', array(
```

Adds a filter comment block.

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php [hunk 6]
```diff
@@ -21,47 +20,47 @@ class WCS_Meta_Box_Related_Orders {
...
+	public static function output( $post_or_order_object ) {
+		$order = ( $post_or_order_object instanceof WP_Post ) ? wc_get_order( $post_or_order_object->ID ) : $post_or_order_object;
 
 		add_action( 'woocommerce_subscriptions_related_orders_meta_box_rows', __CLASS__ . '::output_rows', 10 );
 
-		include_once( dirname( __FILE__ ) . '/views/html-related-orders-table.php' );
+		include_once dirname( __FILE__ ) . '/views/html-related-orders-table.php';
 
-		do_action( 'woocommerce_subscriptions_related_orders_meta_box', $order, $post );
+		do_action( 'woocommerce_subscriptions_related_orders_meta_box', $order );
```
Comment (james-allan) [inline includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: We won't be able to remove the second here as third-parties hooking onto it may be using it and it would cause fatals. Unfortunately, we will need to deprecate the whole filter and continue passing a `post` object as long as we can (while we're still using CPT).

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php [hunk 7]
```diff
@@ -21,47 +20,47 @@ class WCS_Meta_Box_Related_Orders {
...
+		$unknown_orders        = array(); // Orders which couldn't be loaded.
+		$is_subscription       = wcs_is_subscription( $order );
+		$this_order_id         = $order->get_id();
 
 		// If this is a subscriptions screen,
-		if ( wcs_is_subscription( $post->ID ) ) {
-			$this_subscription = wcs_get_subscription( $post->ID );
+		if ( $is_subscription ) {
+			$subscription      = wcs_get_subscription( $order );
+			$this_subscription = wcs_get_subscription( $order->get_id() );
```
Comment (james-allan) [inline includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: These two lines do the same thing right?

**Review by james-allan — CHANGES_REQUESTED** [review]
I've done a pass over the changes for Code review. I left a couple of comments. Next I'll check this branch out and begin testing.

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php [hunk 8]
```diff
@@ -115,24 +114,24 @@ public static function output_rows( $post ) {
 			}
 		}
 
-		$orders_to_display = apply_filters( 'woocommerce_subscriptions_admin_related_orders_to_display', $orders_to_display, $subscriptions, $post );
+		$orders_to_display = apply_filters( 'woocommerce_subscriptions_admin_related_orders_to_display', $orders_to_display, $subscriptions, $order );
```
Comment (james-allan) [inline includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: This change is effectively the reason behind the error you mentioned in the PR description and in the corresponding issue (https://github.com/woocommerce/woocommerce-subscriptions/issues/4417):

```
PHP Notice:  Function ID was called <strong>incorrectly</strong>. Order properties should not be accessed directly. Backtrace: require('wp-admin/edit-form-advanced.php'), do_meta_boxes, WCS_Meta_Box_Related_Orders::output, include_once('/plugins/woocommerce-subscriptions-core/includes/admin/meta-boxes/views/html-related-orders-table.php'), do_action('woocommerce_subscriptions_related_orders_meta_box_rows'), WP_Hook->do_action, WP_Hook->apply_filters, WCS_Meta_Box_Related_Orders::output_rows, apply_filters('woocommerce_subscriptions_admin_related_orders_to_display'), WP_Hook->apply_filters, WC_Subscriptions_Switcher::display_switches_in_related_order_metabox, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.0.) in //wp-includes/functions.php on line 5835
```

This is a breaking change and rather than replace the `$post` variable with an order object we will need to deprecate this filter, only call it if there are third-parties hooking onto it and then trigger a new hook where we can pass the order freely. 

This will look like this roughly. 

```php
if ( has_filter( 'woocommerce_subscriptions_admin_related_orders_to_display' ) ) {
	wcs_deprecated_hook( 'woocommerce_subscriptions_admin_related_orders_to_display', 'subscriptions-core 5.0.0', 'wcs_admin_subscription_related_orders_to_display' );

	/**
	 * Filters the orders to display in the Related Orders meta box.
	 *
	 * This filter is deprecated in favour of 'wcs_admin_subscription_related_orders_to_display'.
	 *
	 * @deprecated subscriptions-core 5.0.0
	 *
	 * @param array   $orders_to_display An array of orders to display in the Related Orders meta box.
	 * @param array   $subscriptions An array of subscriptions related to the order.
	 * @param WP_Post $post The order post object.
	 */
	$orders_to_display = apply_filters( 'woocommerce_subscriptions_admin_related_orders_to_display', $orders_to_display, $subscriptions, get_post( $order->get_id() ) );
}

/**
 * Filters the orders to display in the Related Orders meta box.
 *
 * @since subscriptions-core 5.0.0
 *
 * @param array    $orders_to_display An array of orders to display in the Related Orders meta box.
 * @param array    $subscriptions An array of subscriptions related to the order.
 * @param WC_Order $order The order object.
 */
$orders_to_display = apply_filters( 'wcs_admin_subscription_related_orders_to_display', $orders_to_display, $subscriptions, $order );
```

Comment (james-allan) [reply includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: The `get_post( $order->get_id() )`  will return the order post or the placeholder post on HPOS sites, so on HPOS sites there may be some change in data received, however fully fledged subscription stores running HPOS is far enough down the track that third-parties will likely have replaced uses of this.

This behaviour of post objects becoming unusable is inevitable.

File: includes/admin/meta-boxes/views/html-related-orders-table.php [hunk 9]
```diff
@@ -22,7 +22,7 @@
 			</tr>
 		</thead>
 		<tbody>
-			<?php do_action( 'woocommerce_subscriptions_related_orders_meta_box_rows', $post ); ?>
+			<?php do_action( 'woocommerce_subscriptions_related_orders_meta_box_rows', $order ); ?>
```
Comment (james-allan) [inline includes/admin/meta-boxes/views/html-related-orders-table.php]: assuming that this use to pass a post object, we'll need to deprecate this one too unfortunately.

**Comment by Jinksi** [comment]
> I've done a pass over the changes for Code review. I left a couple of comments. Next I'll check this branch out and begin testing.

Thanks for the feedback ☺️ I'll test it all again after the code changes you've suggested. You may as well delay your testing until then as well 🤷‍♂️

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php (hunk 7 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: Thanks, resolved in cd5e649

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 10]
```diff
@@ -112,36 +113,44 @@ public function remove_meta_box_save( $post_id, $post ) {
 	 */
 	public function enqueue_styles_scripts() {
 		global $post;
+		$ver = WC_Subscriptions_Core_Plugin::instance()->get_library_version();
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php]: Updated to new getter method introduced in #254

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php (hunk 8 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: Thanks for the guidance here @james-allan, appreciate it!

I've resolved this one using your suggestion above in 76eb615, noting that this may break for HPOS-enabled sites using the deprecated hook.

File: includes/admin/meta-boxes/views/html-related-orders-table.php (hunk 9 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-table.php]: Deprecated in d5da9de.

File: includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php (hunk 6 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-related-orders.php]: Deprecated in 25c31be.

**Comment by Jinksi** [comment]
@james-allan I've marked this as ready for another code review, since I've addressed your comments and deprecated hooks. I will continue testing once we have a resolution for #265, since this branch is affected by it.

File: includes/admin/meta-boxes/views/html-related-orders-row.php [hunk 11]
```diff
@@ -11,52 +11,52 @@
...
-			$t_time          = $order->get_date_created()->date_i18n( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ) );
+			$t_time          = $row_order->get_date_created()->date_i18n( get_option( 'date_format' ) . ' ' . get_option( 'time_format' ) );
 			$date_to_display = ucfirst( wcs_get_human_time_diff( $date_created->getTimestamp() ) );
 		} else {
 			$t_time = $date_to_display = __( 'Unpublished', 'woocommerce-subscriptions' );
 		}
 
 		// Backwards compatibility for third-parties using the generic WP post time filter.
-		$date_to_display = apply_filters( 'post_date_column_time', $date_to_display, get_post( $order->get_id() ) );
+		$date_to_display = apply_filters( 'post_date_column_time', $date_to_display, get_post( $row_order->get_id() ) );
```
Comment (Jinksi) [inline includes/admin/meta-boxes/views/html-related-orders-row.php]: Let's deprecate this filter, as it accepts a post parameter. What do you think?

**Comment by haszari** [comment]
> I've marked this as ready for another code review, since I've addressed your comments and deprecated hooks. I will continue testing once we have a resolution for https://github.com/Automattic/woocommerce-subscriptions-core/issues/265, since this branch is affected by it.

FYI @Jinksi I've added `Blocked` label, assuming that this PR is blocked by the infinite recursion issue:

- https://github.com/Automattic/woocommerce-subscriptions-core/issues/265

**Comment by Jinksi** [comment]
> FYI @Jinksi I've added `Blocked` label, assuming that this PR is blocked by the infinite recursion issue:

Thanks @haszari. This issue has now been fixed in #272, so I'll remove the `Blocked` label and begin another round of testing.

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 11 above)
Comment (james-allan) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: Yep that sounds right to me.

**Comment by Jinksi** [comment]
@james-allan It looks like there is now an issue with the metabox not displaying on the Edit Orders screen with HPOS enabled. I'll let you know once it has been resolved.


[`wcs_order_contains_subscription`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/d334429720a4237e4e917c51d55bc31125aa11cc/includes/wcs-order-functions.php#L327) is now returning `false` on the Edit Order screen 🤔

I've added a `Blocked` label due to this PR. A fix has been included in https://github.com/Automattic/woocommerce-subscriptions-core/pull/258#discussion_r1019899441.

**Comment by Jinksi** [comment]
I've removed the `Blocked` label since #258 has been merged into `trunk`.

This PR is ready for review! (again)

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 12]
```diff
@@ -85,8 +84,10 @@ public function add_meta_boxes() {
 		add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_subscription', 'normal', 'low' );
 
 		// Only display the meta box if an order relates to a subscription
-		if ( 'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $post_ID ) && wcs_order_contains_subscription( $post_ID, 'any' ) ) {
-			add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_order', 'normal', 'low' );
+		if ( wcs_order_contains_subscription( $post_or_order_object, 'any' ) ) {
+			// If HPOS is enabled, we need to get the screen id and provide it to add_meta_box().
+			$screen = wcs_is_custom_order_tables_usage_enabled() ? wc_get_page_screen_id( 'shop-order' ) : 'shop_order';
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php:89]: Added this `$current_screen->id === $screen` condition, as it was rendering on other screens (e.g. Edit Product).

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 13]
```diff
@@ -84,9 +83,13 @@ public function add_meta_boxes() {
 
 		add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_subscription', 'normal', 'low' );
 
-		// Only display the meta box if an order relates to a subscription
-		if ( 'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $post_ID ) && wcs_order_contains_subscription( $post_ID, 'any' ) ) {
-			add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', 'shop_order', 'normal', 'low' );
+		// Get "Edit Order" screen ID, which differs if HPOS is enabled.
+		$screen         = wcs_is_custom_order_tables_usage_enabled() ? wc_get_page_screen_id( 'shop-order' ) : 'shop_order';
+		$current_screen = get_current_screen();
+
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php:89]: Added this `$current_screen->id === $screen` condition, as it was rendering on other screens (e.g. Edit Product).

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 14]
```diff
@@ -84,9 +83,13 @@ public function add_meta_boxes() {
...
+		// Only display the meta box if viewing an order that contains a subscription.
+		if ( $current_screen->id === $screen && wcs_order_contains_subscription( $post_or_order_object, 'any' ) ) {
+			add_meta_box( 'subscription_renewal_orders', __( 'Related Orders', 'woocommerce-subscriptions' ), 'WCS_Meta_Box_Related_Orders::output', $screen, 'normal', 'low' );
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-meta-boxes.php]: Added this `$current_screen->id === $screen` condition, as it was rendering on other screens (e.g. Edit Product).

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 11 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: Actually, it'd be good to get your advice here. We don't own this filter (it's a WP filter). 

We could wrap this in an if statement, only fire this if HPOS disabled?

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 14 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-meta-boxes.php]: This condition use to be `'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $post_ID )` was that returning true on product pages?

Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Before 59f50649ad81a3bca51a8740350d6529a46f79c2, I had the statement:

`if ( wcs_order_contains_subscription( $post_or_order_object, 'any' ) ) {`

This was returning throwing an error on product pages since I wasn't checking if it was the edit order screen (rookie WP hook user mistake).

`'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $post_ID )` was removed, since it was accessing `$post_ID` and I removed all references to `$post` or `$post_ID`.

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 15]
```diff
@@ -72,10 +71,10 @@ public function __construct() {
 
 	/**
 	 * Add WC Meta boxes
+	 * @param string $post_type The post type of the current post being edited.
+	 * @param WP_Post|WC_Order $post_or_order_object The post or order currently being edited.
 	 */
-	public function add_meta_boxes() {
-		global $post_ID;
-
+	public function add_meta_boxes( $post_type, $post_or_order_object ) {
```
Comment (james-allan) [inline includes/admin/class-wcs-admin-meta-boxes.php]: While it is unlikely, we can't add new params to publically accessible functions like this in case a third party is calling it.

To introduce new params to this function in a backwards compatible way we need to add placeholders. 

eg

```php
public function add_meta_boxes( $post_type = '', $post_or_order_object = null ) {
```

Then inside the function we'll need to get the object from the global post ID or something if this function receives no object.

File: includes/admin/meta-boxes/views/html-related-orders-row.php [hunk 16]
```diff
@@ -2,7 +2,7 @@
 /**
  * Display a row in the related orders table for a subscription or order
  *
- * @var array $order A WC_Order or WC_Subscription order object to display
+ * @var WC_Order|WC_Subscription $row_order A WC_Order or WC_Subscription order object to display.
```
Comment (james-allan) [inline includes/admin/meta-boxes/views/html-related-orders-row.php]: Unfortunately this isn't something we can change so easily without impacting third-parties backwards compat. 

We can either return to using the `$order` arg or if we want to rename this args we would need to add to this file something like:


```
// Comment saying this is for backwards compat reasons. 
if ( ! isset( $row_order ) ) {
    $row_order = $order
}

```

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 11 above)
Comment (james-allan) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: ah in that case we don't have many options. 

Yeah wrap it in a HPOS check or we have to just stop using it entirely.

File: includes/admin/meta-boxes/views/html-related-orders-table.php [hunk 17]
```diff
@@ -22,7 +23,31 @@
...
+				/**
+				 * Renders renewal order rows in the Related Orders table.
+				 *
+				 * This action is deprecated in favour of 'wcs_related_orders_meta_box_rows'.
+				 *
+				 * @deprecated subscriptions-core 5.1.0
+				 *
+				 * @param WC_Post $post The order post object.
+				 */
+				do_action( 'woocommerce_subscriptions_related_orders_meta_box_rows', wc_get_order( $post ) );
```
Comment (james-allan) [inline includes/admin/meta-boxes/views/html-related-orders-table.php]: is this suppose to just be `$post`? 
```suggestion
				do_action( 'woocommerce_subscriptions_related_orders_meta_box_rows', $post );
```

**Review by james-allan — CHANGES_REQUESTED** [review]
Hey Eric, this PR tests well. I've just left a couple of comments regarding some potential backwards compatibility issues.

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 16 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: I changed this mostly to address my readability concerns, i.e. is this the "global" order for the page or the order for a single row?

But since this will impact backwards compat, I'll revert this to `$order`. Thanks 🙌

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 14 above)
Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: I need to double-check `wc_get_page_screen_id` will work with the earliest supported WC version.

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 15 above)
Comment (Jinksi) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Ah thanks, I didn't consider backwards compat for `public` functions.

Addressed in 23a1429.

File: includes/admin/meta-boxes/views/html-related-orders-table.php (hunk 17 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-table.php]: Yep! Thanks, resolved in 1881951

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 11 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: 👍 updated in 92fac53:

```php
		if ( ! wcs_is_custom_order_tables_usage_enabled() ) {
			// Backwards compatibility for third-parties using the generic WP post time filter.
			// Only apply this filter if HPOS is not enabled, as the filter is not compatible with HPOS.
			$date_to_display = apply_filters( 'post_date_column_time', $date_to_display, get_post( $row_order->get_id() ) );
		}
```

File: includes/admin/meta-boxes/views/html-related-orders-row.php (hunk 16 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: Resolved in d423542.

Do you think it is safe to keep the `WC_Order|WC_Subscription` type change in the docblock?

**Review by james-allan — APPROVED** [review]
Changes look good to me. Thanks for your patience working on this one @Jinksi 💯 

I tested: 

**HPOS:**
- Viewing the edit order screen of a **related order** shows the related orders table. 
- Viewing the edit order screen of a non-related order doesn't show the screen.

**WP Posts:**
- Viewing the edit order screen of a **related order** shows the related orders table. 
- Viewing the edit order screen of a non-related order doesn't show the screen.

Deprecated notices:

- With the WC Subscriptions plugin enabled, I can see the follow deprecated notice:

```
PHP Deprecated:  Hook woocommerce_subscriptions_admin_related_orders_to_display is <strong>deprecated</strong> since version subscriptions-core 5.1.0! Use wcs_admin_subscription_related_orders_to_display instead. in /Users/jamesallan/local-dev/hpos/app/public/wp-includes/functions.php on line 5758
PHP Stack trace: ...
```

So the deprecated warning are working. 👍 There's an issue for this already over on WC Subscriptions. https://github.com/woocommerce/woocommerce-subscriptions/issues/4417

Note: The links in this table are incorrect, however I understand that will be fixed with https://github.com/Automattic/woocommerce-subscriptions-core/pull/269
