### PR TITLE
Use CRUD method to get edit order URL in related orders metabox

### LINKED ISSUE #193: Orders in the related orders table should link to the new Edit Order URL when HPOS is enabled
## Describe the bug

When COT is enabled on a store the proper Order admin url is now: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`
When viewing the related orders table on a subscription, the links still send you to the old URL: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`

From my testing, this URL still appears to work and performing actions (like updating the order status) while on the WP POST Edit Order URL everything seems to work as normal. I think this is because when orders are migrated to the new custom order table, a post with `shop_order_placeholder` post type remains in the post table to link the post.id to the cot.id and keep any actions to the post.id in sync with the order data now in COT.

From this slack thread (p1658827038810479-slack-C9QDV4TL4), we cannot rely on `shop_order_placeholder` being around forever, so we'll need to update this:

> we are not relying on placeholders to be present in anything except for our mitigation of cot.id === post.id . so someone can disable them. but it's not an option in ui at this point
>
> so while we will allow disabling placeholders in the distant future, those users would be part of our experienced user cohort, and we can address that compatibility later.

## To Reproduce

1. Enable the COT feature and turn on COT ([see guide here](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#easy-way))
1. Go into WooCommerce > Settings > Advanced > Custom Data Stores
1. Make sure "Use the WooCommerce orders tables" is enabled
1. Purchase a subscription
1. From WP admin dashboard, go to WooCommerce > Subscriptions and view the new subscription
1. Click on the link to the parent order in the related orders table and notice the URL is different to the URL you would be redirected to if you went to **WP Admin > WooCommerce > Orders** and viewed an order

### Expected behavior

Related orders table links to the correct orders URL when COT is enabled.

### Actual behavior

Related orders table links to the edit post URL when COT is enabled which is relying on `shop_order_placeholder` posts existing on stores to link post IDs to COT IDs.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by Jinksi**
Fixes #193

~Blocked by #223 until we know that the `$order->get_edit_order_url()` will be the correct API for this purpose, see https://github.com/Automattic/woocommerce-subscriptions-core/pull/269#discussion_r1024819934.~

Update: New issue created to address the new HPOS Edit Subscription URL #277

This branch is based on #253.

## Description

This updates the Related Orders table to use the `get_edit_order_url` order method when preparing each related order URL. This allows the URL to be correctly rendered for stores using HPOS and stores using the WP posts table.

## How to test this PR

**HPOS enabled**
1. Enable HPOS feature ([see guide here](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book)).
1. Go into WooCommerce > Settings > Advanced > Custom Data Stores.
1. Make sure "Use the WooCommerce orders tables" is enabled.
1. Purchase a subscription.
1. Go WooCommerce > Subscriptions and view the new subscription.
1. Inspect the link to the parent order in the related orders table.
2. Ensure that the link contains `/admin.php?page=wc-orders` rather than `wp-admin/post.php`.
3. Ensure that clicking the link navigates you to the correct order.

**HPOS disabled**
1. Go into WooCommerce > Settings > Advanced > Custom Data Stores.
1. Make sure "Use the WooCommerce orders tables" is disabled.
1. Go WooCommerce > Subscriptions and view the new subscription.
1. Inspect the link to the parent order in the related orders table.
3. Ensure that clicking the link navigates you to the correct order.

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/meta-boxes/views/html-related-orders-row.php [hunk 1]
```diff
@@ -11,7 +11,7 @@
 ?>
 <tr>
 	<td>
-		<a href="<?php echo esc_url( get_edit_post_link( $row_order->get_id() ) ); ?>">
+		<a href="<?php echo esc_url( $row_order->get_edit_order_url() ); ?>">
```
Comment (Jinksi) [inline includes/admin/meta-boxes/views/html-related-orders-row.php]: This doesn't render correct URLs for related Subscriptions when on the Edit Order screen.

This may or may not be the correct API to use when/if https://github.com/woocommerce/woocommerce/issues/35601 is implemented.

See #223

Comment (mattallan) [reply includes/admin/meta-boxes/views/html-related-orders-row.php]: > This doesn't render correct URLs for related Subscriptions when on the Edit Order screen.

This is fine IMO. There's no correct URL for viewing subscriptions in HPOS yet until #223 is implemented so I've opened a new issue to address this: https://github.com/Automattic/woocommerce-subscriptions-core/issues/277

File: changelog.txt [hunk 2]
```diff
@@ -7,6 +7,7 @@
 * Fix - On HPOS stores, when a subscription is loaded from the database, make sure all core subscription properties are read directly from meta.
 * Update - Refactor our Related Orders data store classes (WCS_Related_Order_Store_Cached_CPT and WCS_Related_Order_Store_CPT) to use CRUD methods to support subscriptions and orders stored in HPOS.
 * Update - Display related orders table when viewing the new "Edit Order" page (HPOS enabled stores).
+* Update - Add support for HPOS edit order URL in related orders table.
```
Comment (mattallan) [inline changelog.txt]:
```suggestion
* Fix - On HPOS stores, make sure the links in the related-orders table redirect to the new Edit Order URL.
```

**Review by mattallan — APPROVED** [review]
Thanks @Jinksi, the code changes in this PR LGTM.

I've tested the following cases:
 -  [x] With WC 7.2 and HPOS enabled, the related orders table is correctly linking orders to the new Edit Order URL: `admin.php?page=wc-orders&id={ID}` (opened separate issue to address subscriptions #277)
 - [x] With WC 7.2 and HPOS disabled, the related orders table is correctly linking both orders and subscriptions to the correct edit post URL: `admin.php?page=wc-orders&id={ID}`
 - [x] With WC 6.8, the related orders table is correctly linking both orders and subscriptions to the correct edit post URL: `admin.php?page=wc-orders&id={ID}`
 - [x] With a really old version of WC (4.0), confirmed the orders and subscriptions still link to the proper edit post URL

@Jinksi I noticed you marked this PR as blocked as there is an issue with the Edit Order URL not working as expecting when trying to view a subscription ID on stores that have HPOS enabled. Rather than leaving this PR open, I've created #277 to address this issue separate once we know more about how we're going to implement a PageController.

I've made a small suggestion in the changelog but apart from that this should be good to merge

**Comment by Jinksi** [comment]
I've just updated from the base branch, which renamed `$row_order` to `$order`.

I inadvertently removed `->get_edit_order_url()` in the merge (848e01b), so added it back in a01e07f.
