### PR TITLE
Only fetch subscription object on subscription admin pages

### LINKED ISSUE #772: WCS_Admin_Meta_Boxes->enqueue_styles_scripts()  attempts to load non-subscription as subscription.
## Describe the bug

`WCS_Admin_Meta_Boxes->enqueue_styles_scripts()` attempts to load a subscription on any admin page that has a global `$post` at the time of `admin_enqueue_scripts` executing, i.e. `/wp-admin/edit.php` or `/wp-admin/edit.php?post_type=aw_workflow`.

This doesn't appear to break anything specific as the default datastores do not return a data object, but does cause an extra query to be run on those pages when HPOS is enabled.  I have not yet tested what occurs if HPOS is not enabled.

## To Reproduce

1. Enable HPOS.
2. Install a query monitor.
3. Visit admin posts listing page.
4. Search for a query to get the order type of the first post of the listing page even though it is a post.  E.g. `SELECT id, type FROM wp_wc_orders WHERE id IN ( 1103554 )`

### Expected behavior

It isn't expected that the `WCS_Admin_Meta_Boxes` would attempt to load a non-subscription.

It is expected that the styles wouldn't attempt to be loaded for the metabox unless the metabox is actually added to the screen.  Or at least verify that this is a screen that needs the subscription before attempting to load the subscription of the global `$post`.

## Product impact
This is a core issue that affects both extensions, but the impact is minor.

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #772 

## Description

This PR makes a slight improvement to performance on non-subscription related admin pages with `$post` globals. eg product, coupon, AW workflow etc. 

Prior to this change, if the `$theorder` global didn't exist but the `$post` global did exist, we would attempt to load a subscription object from that `$post` ID. 

This had 2 effects:

1. Because we are in `$theorder` global scope, we'd be setting the `$theorder` global to the result of `wcs_get_subscription()`.
   - On non-subscription pages this would result in overriding the `null` value and setting it to `false` which is fairly harmless, however not ideal.
2. Making unnecessary database calls to fetch the post type. 

This PR updates this section of the code to make sure we only attempt to set the `$theorder` value where necessary. ie when we're on the subscription page. 

## How to test this PR

1. Install Query Monitor
1. On `trunk` edit a coupon in WP Admin
2. View the query monitor and notice the following query:

```sql
SELECT id, type
FROM wp_wc_orders
WHERE id IN ( 71 )
```

3. On this branch there should be no query. 
4. All functionality on the WooCommerce > Subscriptions and Edit Subscription screen should be unaffected. 

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/class-wcs-admin-meta-boxes.php [hunk 1]
```diff
@@ -136,19 +136,23 @@ public function remove_meta_box_save( $order_id, $order ) {
...
 		$screen    = get_current_screen();
 		$screen_id = isset( $screen->id ) ? $screen->id : '';
 
 		// Get the script version.
 		$ver = WC_Subscriptions_Core_Plugin::instance()->get_library_version();
 
-		if ( wcs_get_page_screen_id( 'shop_subscription' ) === $screen_id && wcs_is_subscription( $theorder ) ) {
+		if ( wcs_get_page_screen_id( 'shop_subscription' ) === $screen_id ) {
+			// If $theorder global is empty, fallback to using the global post object.
+			if ( empty( $theorder ) && ! empty( $GLOBALS['post']->ID ) && wcs_is_subscription( $GLOBALS['post']->ID ) ) {
```
Comment (mattallan) [inline includes/admin/class-wcs-admin-meta-boxes.php]: This is a probably minor thing but something I noticed with this change is we're now calling `wcs_is_subscription( $GLOBALS['post']->ID )` with a post ID inside this condition, which checks the post type by first instantiating a post object using `get_post( $ID )`, then if the type is `shop_subscription`, we satisfy the condition and then call `wcs_get_subscription( $GLOBALS['post']->ID )` to load the subscription into again.

I understand this is necessary to avoid setting the `$theorder` global to null/false, but could we do something like this instead?

```php
if ( empty( $theorder ) && ! empty( $GLOBALS['post']->ID ) ) {
    $subscription = wcs_get_subscription( $GLOBALS['post']->ID );

    if ( $subscription ) {
        $theorder = $subscription;
    } else {
        return;
    }
}
```

**Review by mattallan — APPROVED** [review]
Thanks @james-allan for this PR!

I tested this changes on Edit Coupon and Edit Page admin pages and have confirmed the following query is no longer running on non-subscription pages:

```
SELECT id, type
FROM wp_wc_orders
WHERE id IN ( $ID )
```

I left a non-blocking comment but apart from that, I'm happy to approve this.

File: includes/admin/class-wcs-admin-meta-boxes.php (hunk 1 above)
Comment (james-allan) [reply includes/admin/class-wcs-admin-meta-boxes.php]: Ah nice catch. It seems like a reasonable request given this PR is about improving the performance. If we can delete unnecessary work to determine if a post ID is a subscription, it would be worth it. 

I've pushed https://github.com/Automattic/woocommerce-subscriptions-core/pull/776/commits/98d8dcc16409a9e312ad71d759744b050eaace3f and [4db8574](https://github.com/Automattic/woocommerce-subscriptions-core/pull/776/commits/4db8574bd52d3ad5f826d4890a89d51a86544b9a). Let me know if those changes are inline with what you were thinking.

**Review by mattallan — APPROVED** [review]
Thanks @james-allan for the latest changes, I've tested them again and confirmed this query is now only running on intended subscription pages.

We spoke yesterday about tweaking the code to remove the nested `return;`. Here was what I was thinking:

```php
if ( empty( $theorder ) && ! empty( $GLOBALS['post']->ID ) ) {
	$subscription = wcs_get_subscription( $GLOBALS['post']->ID );

	// If we have a subscription, set it as the global $theorder.
	if ( $subscription ) {
		$theorder = $subscription;
	}
} else {
	$subscription = $theorder;
}

if ( ! wcs_is_subscription( $subscription ) ) {
	return;
}
```

This isn't a blocker by any means and there may be cleaner ways to refactor this.

**Comment by james-allan** [comment]
Thanks @mattallan. That suggestion looks good. I've submitted it in [04ced65](https://github.com/Automattic/woocommerce-subscriptions-core/pull/776/commits/04ced6537f66fc19a3ddf0b369d03e7180bac6a4).

**Review by mattallan — APPROVED** [review]
Thanks @james-allan I've tested the latest changes again and happy to approve this one.
