### PR TITLE
Restore missing filters on Subscriptions listing.

### LINKED ISSUE #323: [HPOS] Viewing Subscriptions admin screen, filters are missing with HPOS enabled.
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) there are custom filters that are not showing.

**CPT**
Screenshot 2022-11-29 at 1 59 36 PM
**HPOS**
Screenshot 2022-11-29 at 2 00 56 PM

Blocked/Resolved by: https://github.com/woocommerce/woocommerce/issues/35753

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. See the filters are missing for Product and Payment method.

### PR DESCRIPTION
**Pull request by brucealdridge**
Fixes #323 

> **Note**
> This PR is targeting the `hpos-admin-ui-support` branch due to the changes required for admin screens in HPOS environments awaiting merge. 

## Description

The custom filters that we add to the Subscriptions list screen were not showing when HPOS is enabled. 

A [new filter has been added](https://github.com/woocommerce/woocommerce/issues/35753#issuecomment-1333835222) in HPOS environments for this purpose `woocommerce_order_list_table_extra_tablenav` additionally the usage of `global $typenow;` has been removed with checks against the order type instead.

Screenshot 2022-11-29 at 1 59 36 PM

## How to test this PR

1. On a HPOS enabled site, go to the Subscriptions listing screen in wp-admin.
2. The filters should be visible.

**NB:** The filters for product/customers are unreadable due to the width. There is [an open issue](https://github.com/Automattic/woocommerce-subscriptions-core/issues/322) for this.

## Product impact

- [x] Added changelog entry (or does not apply)- This will be rolled up into one changelog entry for admin screens working under HPOS.
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

**Comment by brucealdridge** [comment]
Linting is failing due to the source branch [`hpos-admin-ui-support`](https://github.com/Automattic/woocommerce-subscriptions-core/tree/hpos-admin-ui-support)

**Comment by haszari** [comment]
@brucealdridge  I notice that this PR targets a feature branch. I think it's good practice to always explain that up front in the description, as it changes the context for the review (since the changes aren't merging in to trunk, and may depend on changes in other branches that aren't obvious). 

Can you add details to the PR description about the feature branch & your plan for merging these changes? I suggest also opening a PR (draft if necessary) to document the target branch and plans for merge.

**Comment by brucealdridge** [comment]
> Can you add details to the PR description about the feature branch & your plan for merging these changes?

I've added this as a note at the top of the PR description

File: includes/admin/class-wcs-admin-post-types.php [hunk 1]
```diff
@@ -200,12 +205,14 @@ private function posts_clauses_high_performance( $pieces ) {
...
 	/**
 	 * Displays the dropdown for the product filter
+	 *
+	 * @param string $order_type The type of order. This will be 'shop_subscription' for Subscriptions.
+	 *
 	 * @return string the html dropdown element
 	 */
-	public function restrict_by_product() {
-		global $typenow;
+	public function restrict_by_product( $order_type ) {
```
Comment (Jinksi) [inline includes/admin/class-wcs-admin-post-types.php]: We may have to deprecate these non-private functions in case 3PDs are using them.

I'm unsure about this though, as we're adding an argument rather than removing or modifying the argument type. We may have to at least provide a default arg e.g. `$order_type = ''`.

What do you think?

**Review by Jinksi — CHANGES_REQUESTED** [review]
I've requested changes due to the additional argument in non-private functions that could be a breaking change. (https://github.com/Automattic/woocommerce-subscriptions-core/pull/332#discussion_r1040483484).

This tests well, with the filters now rendering with:

- [x] HPOS enabled + no sync
- [x] HPOS enabled + sync
- [x] HPOS disabled

I came across both #334 and #322 with HPOS enabled 👍

File: includes/admin/class-wcs-admin-post-types.php (hunk 1 above)
Comment (mattallan) [reply includes/admin/class-wcs-admin-post-types.php]: Yeah attaching a default to the new argument i.e. `$order_type = ''` should be fine for backward compatibility :)

The `restrict_manage_posts` hook that this function is hooked onto should always send a post type but since this function is public we painfully have to make sure it won't fatal error on peoples sites 😄

Comment (mattallan) [reply includes/admin/class-wcs-admin-post-types.php]: Similar situation for `restrict_by_payment_method` and `restrict_by_customer` functions

**Review by mattallan — APPROVED** [review]
Just making a note that I've looked over these changes and the code looks good (apart from some small backwards compatibility stuff)! I haven't tested it yet but I'm happy to approve it as it's going into a feature branch

Thanks @brucealdridge !

**Comment by mattallan** [comment]
@Jinksi just a heads up that I'm going to take over this PR.

**Comment by mattallan** [comment]
I've made the following changes to this PR:

- [69a4851](https://github.com/Automattic/woocommerce-subscriptions-core/pull/332/commits/69a4851d961968b225735bc262e467e8a6757978) this commit fixes potential backward compatibility issues with 3pds not expecting our `restrict_by_x()` to now require a single paramter.
- [f6aaf56](https://github.com/Automattic/woocommerce-subscriptions-core/pull/332/commits/f6aaf56b587c414122600396c6dfdd2e90ddb447) while testing this I noticed the product filter came after the "Filter" button

**Before**

image

**After**

image

**Comment by mattallan** [comment]
With the latest changes I think this is good to merge into the base branch. I'm going to do that now.
Thanks @brucealdridge for all of the work on this and thanks @Jinksi for the review and test :)
