### PR TITLE
Catch exceptions thrown and caught by WC during subscription-related scheduled actions

### LINKED ISSUE #494: Subscription renewal failure - WCS_Related_Order_Store_Cached_CPT::add_relation()
## Describe the bug

We are getting numerous failed subscription renewal scheduled actions on the dashboard, all with the same error:

failed to finish processing due to the following exception: Argument 1 passed to WCS_Related_Order_Store_Cached_CPT::add_relation() must be an instance of WC_Order, bool given, called in /home/{site name}/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php on line 36

## Product impact
Woocommerce Subscriptions plugin

- [ ] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? yes

### PR DESCRIPTION
**Pull request by james-allan**
Fixes #494

## Description

There are circumstances that can lead to errors like this one when processing renewals.

```
Argument 1 passed to WCS_Related_Order_Store_Cached_CPT::add_relation() must be an instance of WC_Order, bool given, called in /public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php on line 36
```

The cause is unknown. All we know is that for this error to occur `wcs_create_order_from_subscription()` must have failed to load the newly created order with `wc_get_order()` which must have returned `false`. [[code link](https://github.com/woocommerce/woocommerce/blob/49d6b2058ae74913a40aec09787666335cf19e0d/plugins/woocommerce/includes/class-wc-order-factory.php#L54-L57)]

One known reason `wc_get_order()` will return `false` is an exception was thrown in `WC_Order_Factory::get_order()` while the order was being read. What exception? Well we currently don't know because WC catches it, logs it via `wc_caught_exception`. 

This PR improves this by hooking onto `woocommerce_caught_exception` when we're processing subscription related events. If an exception was caught by WC, we'll now log it on the scheduled action and in the failed scheduled action logs. 

| Scheduled action log | WC log |
|--------|--------|
| Screenshot 2023-12-21 at 3 07 40 pm | Screenshot 2023-12-21 at 3 10 34 pm |

Making that change alone wouldn't solve the `WCS_Related_Order_Store_Cached_CPT::add_relation` error I mentioned earlier. 

To fix that, I've changed `wcs_create_order_from_subscription()` so that if it fails to load the order, it will throw an exception, roll back the database, return a `WP_Error`. If you follow that up the chain, that will then lead `process_renewal()` to try another attempt to create the order. If that fails too, then it will throw an final error. 

## How to test this PR

1. Turn on WP post tables if you're using HPOS.
2. Add the following code to your site to trigger the `invalid order` exception.
1. Purchase a subscription.
2. Go to the Tools > Scheduled actions and run the subscription payment action for that subscripotion. 
3. On trunk you'll notice the scheduled action fails with the `WCS_Related_Order_Store_Cached_CPT::add_relation()` error. 
4. On this branch the scheduled action will still fail, however the scheduled action will now have the exceptions that were caught and it will also log the full exception stacktrace in the failed-scheduled-actions logs.

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wc-subscriptions-manager.php [hunk 1]
```diff
@@ -145,8 +145,8 @@ public static function process_renewal( $subscription_id, $required_status, $ord
 				$renewal_order = wcs_create_renewal_order( $subscription );
 
 				if ( is_wp_error( $renewal_order ) ) {
-					// translators: placeholder is an order note.
-					throw new Exception( sprintf( __( 'Error: Unable to create renewal order with note "%s"', 'woocommerce-subscriptions' ), $order_note ) );
+					// translators: placeholder %1 is an order note. %2 is the error message that was thrown.
+					throw new Exception( sprintf( __( 'Error: Unable to create renewal order with note "%1$s". Message: %2$s', 'woocommerce-subscriptions' ), $order_note, $renewal_order->get_error_message() ) );
```
Comment (james-allan) [inline includes/class-wc-subscriptions-manager.php:149]: I just added this change so the scheduled action will actually capture what the error was, rather than just log a generic "it failed" kind of error. 

Screenshot 2023-12-21 at 3 33 57 pm

File: includes/wcs-order-functions.php [hunk 2]
```diff
@@ -250,7 +258,7 @@ function wcs_get_new_order_title( $type ) {
 	$type = wcs_validate_new_order_type( $type );
 
 	// translators: placeholders are strftime() strings.
-	$order_date = strftime( _x( '%b %d, %Y @ %I:%M %p', 'Used in subscription post title. "Subscription renewal order - <this>"', 'woocommerce-subscriptions' ) ); // phpcs:ignore WordPress.WP.I18n.UnorderedPlaceholdersText
+	$order_date = ( new DateTime( 'now' ) )->format( _x( 'M d, Y @ h:i A', 'Order date parsed by DateTime::format', 'woocommerce-subscriptions' ) );
```
Comment (james-allan) [inline includes/wcs-order-functions.php:261]: This was throwing a deprecated phpcs error so I patched it in this branch. This whole function is deprecated since `2.2.0` so there's no need to be too worried about how backwards compatible this replacement is. 

WC replaced their `strftime` with the same approach in https://github.com/woocommerce/woocommerce/pull/31333/files

File: includes/class-wcs-failed-scheduled-action-manager.php [hunk 3]
```diff
@@ -106,6 +114,53 @@ public function log_action_scheduler_failure( $action_id, $error ) {
...
+	public function maybe_attach_exception_listener( $action_id ) {
+		$action = $this->get_action( $action_id );
+
+		if ( ! $action || ! isset( $this->tracked_scheduled_actions[ $action->get_hook() ] ) ) {
+			return;
+		}
+
+		// Add an action to detach the exception listener after the scheduled action has been executed.
+		add_action( 'action_scheduler_after_execute', [ $this, 'clear_exceptions' ] );
+		add_action( 'woocommerce_caught_exception', [ $this, 'handle_exception' ] );
```
Comment (mattallan) [inline includes/class-wcs-failed-scheduled-action-manager.php:147]: Do we need to `remove_action` this hook on `action_scheduler_after_execute` as well?

Something I noticed is that we're only clearing the list of exceptions once they're logged or on the  `action_scheduler_after_execute` hook, but shouldn't we clear them on the `begin` action as well? 

While it's very unlikely... what if the following scenario ever happens within the same request, won't we end up logging incorrect data?

1. Job 1 starts (successful): `action_scheduler_begin_execute` - exception listeners added
3. Job 1 finishes: `action_scheduler_after_execute` cleared
4. `woocommerce_caught_exception` is thrown by some 3rd party code and we've added it to the list of exceptions
5. Job 2 starts (failure): `action_scheduler_begin_execute`
6. `woocommerce_caught_exception`
7. Job 2 `log_action_scheduler_failure` runs and logs both exceptions from step 4 and 6 when only 6 is relevant to the scheduled action?

**Review by mattallan — APPROVED** [review]
Nice changes @james-allan!

I especially like the changes you made to `wcs_create_order_from_subscription()` which makes it so we're not going to throw an exception, rollback the DB and return a WP_Error as well.
Not sure if this was intentional but this also means we've got a built-in retry system now for when these errors occur! This is becuase [`process_renewal()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/5abcf9aac4e53ad9bdcf3752a34a04ae42261bac/includes/class-wc-subscriptions-manager.php#L143-L146) will try recreate the order again when a WP_Error is returned 👌 

I've tested the changes and reviewed the code and it all looks good!

I've just left a comment regarding removing the action listeners once we're done with them and/or clearing the list of exceptions at the beginning of the scheduled action.

File: includes/class-wcs-failed-scheduled-action-manager.php (hunk 3 above)
Comment (james-allan) [reply includes/class-wcs-failed-scheduled-action-manager.php:147]: yeah thats a good point. You can kind of tell from the comment above this line that is what I intended. 

```
// Add an action to detach the exception listener after the scheduled action has been executed.
```

Except I don't detach the listener at all, I just empty the exceptions. I'm not sure why I did that though. 🤔 

I'll fix that up though and retest.

Comment (mattallan) [reply includes/class-wcs-failed-scheduled-action-manager.php:147]: > Except I don't detach the listener at all, I just empty the exceptions. I'm not sure why I did that though. 🤔

Yeah I noticed that as well. I thought maybe your initial approach was detaching the listeners but then moved away from that before pushing the code and forgot to update the comment.

Comment (james-allan) [reply includes/class-wcs-failed-scheduled-action-manager.php:147]: I also confirmed your theory. Doing something like this: 


```php
ActionScheduler_QueueRunner::instance()->process_action( 51111 );
wc_caught_exception( new Exception( 'Unrelated error' ) );
ActionScheduler_QueueRunner::instance()->process_action( 51119 );
```

Where 51111 is the scheduled action ID for a successful action and 51119 fails. 

Screenshot 2024-01-11 at 1 34 19 pm

You can see that because the first action doesn't detach itself, the exception thrown in between is logged for the second one.

Comment (james-allan) [reply includes/class-wcs-failed-scheduled-action-manager.php:147]: I've pushed https://github.com/Automattic/woocommerce-subscriptions-core/pull/552/commits/1c816bbd3a0dce2b9373b66a7bd665d13d371f84 should detach the exception listener when the action either successfully exceutes (`action_scheduler_after_execute`) or fails (`action_scheduler_failed_action` or `action_scheduler_failed_execution`)

Comment (mattallan) [reply includes/class-wcs-failed-scheduled-action-manager.php:147]: Thanks @james-allan that's amazing you were able to reproduce the theory! I'll give this another review/test

**Review by mattallan — APPROVED** [review]
Really nice work on this PR @james-allan !!

I've tested the latest changes:
- [x] Unexpected reading in order object
- [x] Running scheduled action for subscription that doesn't exist
- [x] Successful test

Do we want a changelog entry for this one?

Maybe something like:
```
* Update - Log all exceptions caught by WooCommerce while processing a subscription scheduled action.
```

/shrug

**Comment by james-allan** [comment]
> Do we want a changelog entry for this one?
> Maybe something like: ...

Sounds good. I've pushed in https://github.com/Automattic/woocommerce-subscriptions-core/pull/552/commits/9cc7f19554ad158075c37a10273ff47cda43f284
