### PR TITLE
[HPOS] Refactor `WCS_Meta_Box_Schedule::save` to fix PHP notices that occur when updating an order via the Edit Order page

### LINKED ISSUE #196: With COT enabled, multiple PHP notices are displayed when updating/saving an order linked to a subscription
## Describe the bug

With COT enabled, updating/saving an order via the Edit Order page results in the following PHP notices:

image

The backtrace points to the following functions which are accessing subscription/order properties which:
 - `WCS_Admin_Meta_Boxes->remove_meta_box_save`
 - `WCS_Meta_Box_Schedule::save`
 - `WCS_Meta_Box_Subscription_Data::save`

We should change these to just `$object->get_type()`.

## To Reproduce

1. Enable COT on your store (see [guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Purchase a subscription
3. Make note of the parent order ID
4. Got to **WooCommerce > Orders > Edit Order** for the order just purchased
5. Update the status of the order to on-hold and hit "Update"
6. Notice the errors at the top of the page

### Expected behavior

No errors are to be shown after updating an order.

### Fixed by

- [x] #280 
- [x] #281 
- [x] #282

### PR DESCRIPTION
**Pull request by Jinksi**
Partially fixes #196

This branch is based on #280.

## Description

This PR fixes PHP notices related to `WCS_Meta_Box_Schedule::save` that occur when updating an order via the Edit Order page with HPOS enabled.

## How to test this PR

0. [Enable HPOS](https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#how-to-enable-hpos).
2. Purchase a Subscription product, noting the order ID.
3. Go to WooCommerce → Orders and navigate to the order's Edit Order page.
4. Select a new order **status** (processing/pending payment) and click update.
5. The order should update successfully and you should not see PHP notices related to **`WCS_Meta_Box_Schedule::save`**.
		(There may be others, e.g. `WCS_Meta_Box_Subscription_Data::save`).
3. Go to WooCommerce → Subscriptions and navigate to a subscription's Edit Subscription page.
4. Select a new subscription status (on hold/active) and click update.
5. The subscription should update successfully and you should not see PHP notices related to **`WCS_Meta_Box_Schedule::save`**.
4. Change the subscription billing period and interval and click update. The change should be reflected.
6. Disable HPOS and repeat steps 2-8
	(WC Settings → Advanced → Custom data stores →  Use the WordPress posts table)

**Note**: you may see the following error when setting a Subscription status to `on-hold` with HPOS enabled, syncing disabled. A new issue has been created for this: #293

```
Invalid data. First parameter was empty when passed to update_dates().
```

## Product impact

- [x] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php [hunk 1]
```diff
@@ -72,7 +77,7 @@ public static function save( $post_id, $post ) {
 			try {
 				$subscription->update_dates( $dates, 'gmt' );
 
-				wp_cache_delete( $post_id, 'posts' );
+				wp_cache_delete( $post_or_order_id, 'posts' );
```
Comment (Jinksi) [inline includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: This will need to be removed or replaced to work with HPOS.

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php [hunk 2]
```diff
@@ -31,20 +31,25 @@ public static function output( $post ) {
...
+	 * @see woocommerce_process_shop_order_meta
+	 *
+	 * @param int $post_or_order_id
+	 * @param WP_Post|WC_Order $post_or_order_object
 	 */
-	public static function save( $post_id, $post ) {
+	public static function save( $post_or_order_id, $post_or_order_object ) {
 
-		if ( 'shop_subscription' === $post->post_type && ! empty( $_POST['woocommerce_meta_nonce'] ) && wp_verify_nonce( wc_clean( wp_unslash( $_POST['woocommerce_meta_nonce'] ) ), 'woocommerce_save_data' ) ) {
+		if ( wcs_is_subscription( $post_or_order_id ) && ! empty( $_POST['woocommerce_meta_nonce'] ) && wp_verify_nonce( wc_clean( wp_unslash( $_POST['woocommerce_meta_nonce'] ) ), 'woocommerce_save_data' ) ) {
```
Comment (Jinksi) [inline includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: I prefer to use early returns to improve readability, e.g:

```php
if ( ! wcs_is_subscription( $post_or_order_id ) ) {
  return false;
}
```

Need to check if the returned value is of important to the `woocommerce_process_shop_order_meta` hook.

Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: Updated in 9debb2d

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php [hunk 3]
```diff
@@ -31,53 +31,63 @@ public static function output( $post ) {
...
 	/**
 	 * Save meta box data
+	 *
+	 * @see woocommerce_process_shop_order_meta
+	 *
+	 * @param int $post_or_order_id
+	 * @param WP_Post|WC_Order $post_or_order_object
 	 */
-	public static function save( $post_id, $post ) {
+	public static function save( $post_or_order_id, $post_or_order_object ) {
```
Comment (Jinksi) [inline includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: I am renaming these params to make it clear that it ~could be a post or~ is an order.

I don't think renaming will have an impact on backwards compat for 3PD that may be calling this public function.

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php [hunk 4]
```diff
@@ -31,53 +31,63 @@ public static function output( $post ) {
...
-			}
+		if ( empty( $_POST['woocommerce_meta_nonce'] ) || ! wp_verify_nonce( wc_clean( wp_unslash( $_POST['woocommerce_meta_nonce'] ) ), 'woocommerce_save_data' ) ) {
+			return;
+		}
 
-			if ( ! empty( $_POST['_billing_period'] ) ) {
-				update_post_meta( $post_id, '_billing_period', wc_clean( wp_unslash( $_POST['_billing_period'] ) ) );
-			}
+		if ( isset( $_POST['_billing_interval'] ) ) {
+			$post_or_order_object->update_meta_data( '_billing_interval', wc_clean( wp_unslash( $_POST['_billing_interval'] ) ) );
```
Comment (Jinksi) [inline includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: Changed this from `update_post_meta` to order CRUD method.

File: changelog.txt [hunk 5]
```diff
@@ -6,6 +6,7 @@
 * Fix - On HPOS stores, when querying for subscriptions with wcs_get_orders_with_meta_query() with status 'any', ensure that wc_get_orders() queries for subscription statuses.
 * Fix - On HPOS stores, when saving a subscription make sure subscription properties (ie `_requires_manual_renewal`) are saved to the database.
 * Fix - On HPOS stores, when a subscription is loaded from the database, make sure all core subscription properties are read directly from meta.
+* Fix - Refactor `WCS_Meta_Box_Schedule::save` to support HPOS stores, fixing a PHP warning notice when updating an order via the Edit Order screen.
```
Comment (Jinksi) [inline changelog.txt:11]: Note: will merge this changelog entry with the other PR related to #196

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php (hunk 1 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: Resolved in 147ca0f

File: includes/admin/meta-boxes/class-wcs-meta-box-schedule.php (hunk 4 above)
Comment (Jinksi) [reply includes/admin/meta-boxes/class-wcs-meta-box-schedule.php]: Update: changed to subscription CRUD method in 52d0064

**Comment by shendy-a8c** [comment]
The `$subscription->save();` line has indentation issue.

Screenshot 2022-11-22 at 00 36 29

**Comment by shendy-a8c** [comment]
Saving subscription still shows other notices but not one related to `WCS_Meta_Box_Schedule`, so that's good.

**Comment by shendy-a8c** [comment]
When applying https://github.com/Automattic/woocommerce-subscriptions-core/pull/292, I got this error when changing status to on-hold:
```
Invalid data. First parameter was empty when passed to update_dates().
```

Screenshot 2022-11-22 at 00 43 51

Do you also get that?

**Comment by shendy-a8c** [comment]
Also, this might be outside the scope of this PR, but that function `WCS_Meta_Box_Schedule::save()` does not make sure `$order`'s id is the same as the passed `$order_id`. Maybe it's intended, so that function can be used to copy an order overriding another order with different id?

**Comment by Jinksi** [comment]
> When applying #292, I got this error when changing status to on-hold:
> 
> ```
> Invalid data. First parameter was empty when passed to update_dates().
> ```

@shendy-a8c Yes, I also see this now (I've merged the changes introduced in #292 from `trunk`). With HPOS enabled, syncing disabled.

This could be due to the missing **Schedule** metabox. I'll investigate to see if this is a new issue.

---

**Update:**
I started investigating before realising that the `WCS_Meta_Box_Schedule` class causes this issue 😆 .~I will look at fixing in this PR if it is simple enough~

#293 created. This issue may be blocked by #223.

**Review by shendy-a8c — APPROVED** [review]
Approving...

Also, weird that the indentation issue wasn't caught by phpcs.
