### PR TITLE
Replace trivial instances of `get_post_type()` usage (take 1)

### LINKED ISSUE #288: [HPOS] Replace `get_post_type()` with WC_Data_Store::load( 'subscription' )->get_order_type( $id )
## Describe the bug

To support subscriptions stored in different data stores, we need to replace all cases of `get_post_type()` with `WC_Data_Store::load( 'subscription' )->get_order_type( $id )`.

Doing a search of `get_post_type(` in `subscriptions-core` code there's 15 instances of this still being used.

In #153 we only targetted code which used this function on WC Orders, but as part of tackling this issue we should replace all cases.

---

#### Updating `get_post_type( $subscription_id )`

```
'shop_subscription' == get_post_type( $post_id )
```

Replace with:

```
'shop_subscription' === WC_Data_Store::load( 'subscription' )->get_order_type( $id )
```

#### Updating `get_post_type( $product_id )`

I could only find one instance where we're using `get_post_type()` with product ID inside `user_can_not_delete_subscription()`

```
0 === strpos( get_post_type( $args[2] ), 'product' )
```

The issue with`WC_Data_Store::load( 'product' )->get_product_type( $id )` is that it formats product types i.e. `'product_variation'` is returned as just `'variation'` so there's not a simple one-to-one replacement for this one.

We can probably just ignore this one case for now.

### PR DESCRIPTION
**Pull request by shendy-a8c**
Partially fixes https://github.com/Automattic/woocommerce-subscriptions-core/issues/288.

## Description

This PR replaces the usage of `get_post_type()` with `WC_Data_Store::load( 'subscription' )->get_order_type( $id )`. There are more `get_post_type()` to be replaced but in this PR, I just replaced ones that are trivial enough.

## How to test this PR

For `WC_Subscriptions_Synchroniser::get_sign_up_fee()`

## Product impact

- [ ] Added changelog entry (or does not apply)
- [ ] Will this PR affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Will this PR affect WooCommerce Payments? yes/no/tbc, add issue ref
- [ ]  Added deprecated functions, hooks or classes to the [spreadsheet](https://docs.google.com/spreadsheets/d/1xw9xszcPMnWsp4C8OKZMsLzZob7tOmWT7qMqmEIq314/edit#gid=0)

### CODE REVIEW

File: includes/class-wc-subscriptions-synchroniser.php [hunk 1]
```diff
@@ -1529,7 +1529,7 @@ public static function prefill_order_item_meta( $item, $item_id ) {
 	public static function get_sign_up_fee( $sign_up_fee, $order, $product_id, $non_subscription_total ) {
 		_deprecated_function( __METHOD__, '2.0', __CLASS__ . '::get_synced_sign_up_fee' );
 
-		if ( 'shop_order' == get_post_type( $order ) && self::order_contains_synced_subscription( wcs_get_objects_property( $order, 'id' ) ) && WC_Subscriptions_Order::get_subscription_trial_length( $order ) < 1 ) {
+		if ( 'shop_order' === WC_Data_Store::load( 'subscription' )->get_order_type( $order ) && self::order_contains_synced_subscription( wcs_get_objects_property( $order, 'id' ) ) && WC_Subscriptions_Order::get_subscription_trial_length( $order ) < 1 ) {
```
Comment (mattallan) [inline includes/class-wc-subscriptions-synchroniser.php]: Because we're checking for `'shop_order'` we should load the orders data store.

```suggestion
		if ( 'shop_order' === WC_Data_Store::load( 'order' )->get_order_type( $order ) && self::order_contains_synced_subscription( wcs_get_objects_property( $order, 'id' ) ) && WC_Subscriptions_Order::get_subscription_trial_length( $order ) < 1 ) {
```

**Review by mattallan — CHANGES_REQUESTED** [review]
A small change request but apart from that, this is also good to be merged IMO.

Just needs a changelog entry :)
Thanks @shendy-a8c

**Review by mattallan — APPROVED** [review]
I've reviewed these changes again and it looks good. I know this PR is still in draft but I think it's good to be merged now :)

**Comment by shendy-a8c** [comment]
Nice! I was struggling to come up with testing instructions. Hence, it's still being a draft.

I added a changelog entry:
```
* Update - Replace `get_post_type()` calls in `WC_Subscriptions_Synchroniser` for HPOS support.
```

Even though this PR also removes `get_post_type()` in `WCS_Cached_Data_Manager` and `WCS_Download_Handler` but there are still some `get_post_type()` in those classes, so changelog entries can be added in a separate PR until they are completely removed from those classes.

**Comment by mattallan** [comment]
> Even though this PR also removes get_post_type() in WCS_Cached_Data_Manager and WCS_Download_Handler but there are still some get_post_type() in those classes, so changelog entries can be added in a separate PR until they are completely removed from those classes.

Oh!! I thought this PR was updating all the remaining instances of `get_post_type()` instances. My concern with splitting the one `replace get_post_type()` issue into 3 PRs is they don't necessarily need 3 individual changelog entries.

With that in mind, the new changelog entry added in this PR doesn't really make sense to include because it's changing a line in function that has been deprecated for a long time 😅

```
* Update - Replace `get_post_type()` calls in `WC_Subscriptions_Synchroniser` for HPOS support.
```

In your next PR do you mind updating all remaining `get_post_type()` where we pass a subscription ID and then have a combined changelog entry like (similar to what we did when we updated orders get post type code):

```
* Dev - Replace code using get_post_type( $subscription_id ) with WC Data Store get_order_type().
```

**Comment by shendy-a8c** [comment]
That makes sense. Will do. There are still some `get_post_type()` that need to be replaced. This PR is just to make it small. I will update the changelog in the next PR.
