### PR TITLE
Fix typo in confirmation alert when users remove an item from a subscription.

### LINKED ISSUE #438: Typo in confirmation alert when users remove an item from a subscription
## Describe the bug

There's a typo in the notice shown to users when they remove an item from their subscription. 

Screenshot 2023-05-04 at 4 29 10 pm

There's a missing "to". The message should read:

> **Are you sure you want to remove this item from your subscription?**

## To Reproduce

1. Purchase a subscription with at least 2 separate line items. (See example screenshot below)
2. Go to the **My Account > Subscriptions** page.
3. Click the **x** next to one of the items. 
4. You should see the notice shown above. 

Screenshot 2023-05-04 at 4 29 47 pm

The line in question lives here:

https://github.com/Automattic/woocommerce-subscriptions-core/blob/acf0ec932bea59c92bab0fe2a469a9313b3b6f05/templates/myaccount/subscription-totals-table.php#L35

### PR DESCRIPTION
**Pull request by Mayisha**
Fixes #438 

### Description
There's a typo in the notice shown to users when they remove an item from their subscription. The notice is missing a `to` between `you` and `want`.

```
Are you sure you want remove this item from your subscription?
```

### Steps to reproduce

1. Purchase a subscription with at least 2 separate line items. 
2. Go to the **My Account > Subscriptions** page.
3. Click the `x` next to one of the items.
4. You should see the notice as below.
```
Are you sure you want to remove this item from your subscription?
```

### CODE REVIEW

File: templates/myaccount/subscription-totals-table.php [hunk 1]
```diff
@@ -77,7 +76,8 @@
 				<?php
 			}
 
-			if ( $subscription->has_status( array( 'completed', 'processing' ) ) && ( $purchase_note = get_post_meta( $_product->id, '_purchase_note', true ) ) ) {
+			$purchase_note = get_post_meta( $_product->get_id(), '_purchase_note', true );
```
Comment (james-allan) [inline templates/myaccount/subscription-totals-table.php:79]: Just flagging that this could be updated to `$_product->get_purchase_note()` but there's a lot of post meta calls related to products so I think this is fine to leave it for now given this is how the code was prior to your changes and you're just fixing a coding standards violation.

**Review by james-allan — APPROVED** [review]
Thanks for going the extra mile and cleaning up the other coding standard issues in this PR.

The changes look good and it's nice to see this small typo fixed after so long. 💯
